### ISSUE TITLE
 WindowsDefender consider SqueakSSL.dll as a virus and delete it

### ISSUE THREAD

**Issue by jecisc** [OpenSmalltalk/opensmalltalk-vm#154]
When I extract a Pharo VM, the SqueakSSL.dll is always deleted because it is considered as a trojan.

I am not the only one, three other people reported it on the ML or on Discord.

I don't know how to correct that but it is really bothering. 

Related pharo issue: https://pharo.fogbugz.com/f/cases/20500/WindowsDefender-consider-SqueakSSL-dll-as-a-virus-and-delete-it

**Comment by fniephaus** [comment]
Closed in favor of #152.
