### ISSUE TITLE
Pharo build failures caused by deployment step

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#160]
Example from [this build](https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/jobs/291133215#L7731):
> Uploading ./pharo-linux-x86_64itimer-201710221351-1a23fe1.zip to pharo.files.org//appli/files.pharo.org/vm/pharo-spur64/linux
Warning: Permanently added the RSA host key for IP address '193.51.193.142' to the list of known hosts.
Uploading ./pharo-linux-x86_64itimer-201710221351-1a23fe1.zip to pharo.files.org//appli/files.pharo.org/vm/pharo-spur64/linux/latest.zip
scp: /appli/files.pharo.org/vm/pharo-spur64/linux/latest.zip: Permission denied
Script failed with status 1

**Comment by fniephaus** [comment]
The issue persists. Reverting my latest changes and disabling Pharo deploy to unblock the build pipeline. Please fix @estebanlm.

**Comment by estebanlm** [comment]
I know Christophe was working on it, but I do not know if he finished (And I didn't have the time to work on it myself). I guess next week we will have a solution.

**Comment by fniephaus** [comment]
No problem. Change [this](https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/ebe0000158dba326a75ba96866edaf7187e62d44#diff-354f30a63fb0907d4ad57269548329e3R25) to enable Pharo deployment again when Christophe or you have time to fix it.

**Comment by estebanlm** [comment]
this is done, isn't @fniephaus ?

**Comment by estebanlm** [comment]
I mean, now we have the packaging problem (which I will fix today), but this is done, AFAIK

**Comment by fniephaus** [comment]
Yes, this is fixed....
