### ISSUE TITLE
Election to replace special selector #blockCopy: in closure VMs and images

### ISSUE THREAD

**Issue by ghost** [OpenSmalltalk/opensmalltalk-vm#163]
#blockCopy: is nearly obsolete. It does not currently merit to be a special selector in **closure** VMs.

3 good candidates are:
* at:ifAbsent:
* ,
* nextPutAll:

You are welcome to propose new selectors.

**Comment by nicolas-cellier-aka-nice** [comment]
But I don't see blockCopy in Squeak trunk for example:
`Smalltalk specialSelectorNames` -> `#(#+ #- #< #> #<= #>= #= #~= #* #/ #\\ #@ #bitShift: #// #bitAnd: #bitOr: #at: #at:put: #size #next #nextPut: #atEnd #== #class #~~ #value #value: #do: #new #new: #x #y)`

It seems to me that it has been replaced by `#~~` so it's more an image side modification than a VM modification.

I thus close this report. Reopen it if I missed something.

**Comment by ghost** [comment]
OK, I'll modify my Squeak 5.1 image to do this.

**Comment by nicolas-cellier-aka-nice** [comment]
In case it's useful, see System-ul.936.mcz and Compiler-eem.333.mcz and maybe a few others in trunk
