### ISSUE TITLE
Fix building SDL2DisplayPlugin on Linux

### ISSUE THREAD

**Issue by ronsaldo** [OpenSmalltalk/opensmalltalk-vm#169]
SDL2DisplayPlugin on Linux CI fails with:

libtool: link: gcc -m64 -shared -fPIC -DPIC .libs/SDL2DisplayPlugin.o -lSDL2 -m64 -O2 -msse2 -Wl,-z -Wl,now -Wl,-soname -Wl,SDL2DisplayPlugin.so -o .libs/SDL2DisplayPlugin.so

/usr/bin/ld: cannot find -lSDL2

TODO: Find the proper place and way for adding -L<placeto the thirdparty cache/lib> so that the plugin can be built.

**Comment by fniephaus** [comment]
Is this still a problem?

**Comment by estebanlm** [comment]
nope

**Comment by fniephaus** [comment]
Thanks!
