### ISSUE TITLE
Latest 32bit macOS VM segfaults on Travis

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#178]
Hi all,

I'm not up-to-date with the latest macOS display/event changes, but there seems to be a problem with the current code which causes the VM to segfault on Travis (example [1]). Actually, I tried out a VM from Nov 30 and that also seems to segfault, so the problem was introduced at least a month ago. Note that the segfaulting VM runs headful and is supposed to update a base image to produce Squeak-trunk. Can anyone look into this?

Best,
Fabio

[1] https://travis-ci.org/squeak-smalltalk/squeak-app/jobs/320661515#L198

**Comment by fniephaus** [comment]
Any updates on this, @johnmci? Older vms that don't have this issue have problems when saving projects, so it'd be great if we can update the trunk vms soon with a fix for this.

**Comment by johnmci** [comment]
Can someone send a script to run to recreate the problem. Also need a pointer/url  to the image in question

**Comment by fniephaus** [comment]
I'm afraid you won't be able to reproduce the problem locally as your machine has a display and OpenGL enabled. Not sure how Travis's CI workers are configured, but I could try out a few things in a shell for you if that'd help.
Anyway, here's the base image for `Squeak-trunk`: http://files.squeak.org/base/Squeak-trunk/base.zip
And here the VM that currently fails on Travis: http://files.squeak.org/base/Squeak-trunk/vm-macos.zip

The VM is invoked via:
```bash
"${SMALLTALK_VM}" "${TMP_DIR}/Squeak.image" \
      "${TRAVIS_BUILD_DIR}/prepare_image.st" "Squeak-trunk"
```

`prepare_image.st` is located [here](https://github.com/squeak-smalltalk/squeak-app/blob/squeak-trunk/prepare_image.st).
