### ISSUE TITLE
build.linux*/*/*/mvm files being ignored

### ISSUE THREAD

**Issue by eliotmiranda** [OpenSmalltalk/opensmalltalk-vm#20]
make a change to any of build.linux32ARMv7/newspeak.*/build*/mvm (i.e. changing INSTALLDIR=nscogspurlinuxhtARM to INSTALLDIR=nscogspurlinuxhtARMv7) and then say git status.  No joy!

I need to check in these fixes.  can some kind soul who understands the .gitignore conventions fix .gitignore to not ignore at the least the mvm files three levels down in the build.linux* builds?

**Comment by krono** [comment]
I cannot reproduce.

When I change `build.linux32ARMv6/newspeak.cog.spur/build`
(eg, 
````diff
-INSTALLDIR=nscogspurlinuxhtRPi
+INSTALLDIR=nscogspurlinuxhtRPiA
````
), then I get a "modified":

````
On branch Cog
Your branch is up-to-date with 'origin/Cog'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   mvm

no changes added to commit (use "git add" and/or "git commit -a")
````
whithout touching the `.gitignore`

**Comment by fniephaus** [comment]
Same here, I can't reproduce the problem. Do you happen to have a global `.gitignore`?

**Comment by eliotmiranda** [comment]
Sorry guys, I mentioned the wrong directly.  I'm seeing the issue with build.linux32ARMv7newspeak./build/mvm

**Comment by fniephaus** [comment]
Works for me:
![image](https://cloud.githubusercontent.com/assets/2368856/16471932/7ecbd3e2-3e60-11e6-8216-ca5c92ea2e85.png)

**Comment by eliotmiranda** [comment]
Seems to be fixed :-)  Thanks.

**Comment by fniephaus** [comment]
What was the problem?
