### ISSUE TITLE
OpenSSL fails to build on macOS

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#208]
I had to clear the build cache and now Travis tries to build OpenSSL from scratch and that is failing repeatedly for some unknown reason ([example build](https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/jobs/336209100#L7345)).

/cc @estebanlm

**Comment by charig** [comment]
The problem seems to be the makefile command: 
"cd builddbg/third-party/openssl-1.0.2m \

		&& ./Configure darwin-i386-cc --prefix='/Users/guidochari/Documents/Projects/CogNOS/opensmalltalk-vm/.thirdparty-cache/macOS/i386' shared | grep -C10 "Error" \

		&& LDFLAGS='-Wl,-rpath,@executable_path:@executable_path/Plugins' make | grep -C10 "Error" \

		&& make install".

If there is no "error" line to output, grep outputs 1 and && fails. If I run the 3 commands one by one by hand the compilation passes.

**Comment by charig** [comment]
Same happens with Cairo

**Comment by fniephaus** [comment]
Thanks, @charig. I've removed the `grep` commands and hope this works now...
