### ISSUE TITLE
Don't hardcode gcc in win32 Makefile

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [OpenSmalltalk/opensmalltalk-vm#21]
We should not hardcode gcc in build.win32/common/Makefile*
CC:= gcc
LD:= gcc

It prevents overriding at command line.
For example, when compiling with a recent cygwin:

CC=i686-w64-mingw32-gcc ./mvm -A

Eventually we could set
LD := $(CC)

**Comment by timfel** [comment]
If you check the .appveyor.yml you can see that we actually work around this to compile with recent cygwin :)

**Comment by timfel** [comment]
So 👍

**Comment by nicolas-cellier-aka-nice** [comment]
Oh yes, I see all the ugly sed in .travis_build.sh
My bad this does not work as intended:
CC=i686-w64-mingw32-gcc make

But this works and overrides CC:=gcc definition:
make CC=i686-w64-mingw32-gcc

Of course DLLTOOL, DLLWRAP, WINDRES, ... have to be changed too.
There should be a way to mimic the toolchain of cmake via gnu make.
So at least, we need to pass additional options to make thru mvm

**Comment by nicolas-cellier-aka-nice** [comment]
By reading mvm source I see that there is a possibility already to pass options to make, after -- argument (mind properly escaping quotes if any):

mvm -f -- CC=i686-w64-mingw32-gcc DLLTOOL=i686-w64-mingw32-dlltool DLLWRAP=i686-w64-mingw32-dllwrap RC=i686-w64-mingw32-windres EXPORT=--export-all-symbols

So it remains to fix:
the STDLIBS -lws2_32 instead of -lwsock2, no -lcrtdll (since we use LD=$(CC))
the -mno-cygwin and -mwin32 flags (maybe replace with -m32)

**Comment by nicolas-cellier-aka-nice** [comment]
I close the issue because the mvm -- options is enough for working the problem around.
However the whole file should be updated to use something newer than legacy cygwin 1.4.x which is less than easy to find/download/install nowadays.
