### ISSUE TITLE
pharo.cog.spur configure error: C compiler cannot generate executables

### ISSUE THREAD

**Issue by melkyades** [OpenSmalltalk/opensmalltalk-vm#211]
When building for linux32x86 on ubuntu17.04/64-bits. I _do_ have a cross compiler and can generate 32bit binaries with -m32

---

[...]/opensmalltalk-vm/spursrc
[...]/opensmalltalk-vm/src/plugins
checking sanity of generated src directory... okay
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu

Configuring Squeak  (.-) for i686-pc-linux-gnu

checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m32
checking for C compiler default output file name... configure: error: C compiler cannot create executables

**Comment by krono** [comment]
Can you make sure you have all libraries you need in :i386 flavor? example is in the `.travis-install.sh`: https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/.travis_install.sh#L16

**Comment by melkyades** [comment]
The following worked, I'm afraid I'll never know which one was the cause of the problem. 

sudo apt install libc6-dev:i386 libasound2:i386 libasound2-dev:i386 libssl-dev:i386 libssl0.9.8:i386 libx11-dev:i386 libsm-dev:i386 libice-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev:i386 libxext-dev:i386 libglapi-mesa:i386 uuid-dev:i386 libcurl3-dev:i386
