### ISSUE TITLE
isReadOnlyObject should return false when writebarrier is not supported

### ISSUE THREAD

**Issue by dionisiydk** [OpenSmalltalk/opensmalltalk-vm#217]
Object is definitely not readonly when VM do not support write barrier. But right now it will be primitive failure.

For example it makes impossible to modify classes in Pharo 7 on ARM VM. 
Pharo 7 checks instances for readonly before migrating them

**Comment by dionisiydk** [comment]
Probably it is image side logic. 
So close if it is not related to VM

**Comment by clementbera** [comment]
It's image-side logic IMO
