### ISSUE TITLE
Fallback window size on Mac is too small

### ISSUE THREAD

**Issue by pavel-krivanek** [OpenSmalltalk/opensmalltalk-vm#288]
Related issue: https://pharo.fogbugz.com/f/cases/20094/Headless-mode-breaks-image

When the image is saved in headless mode, the window size is set to extension 10@10. This value is too small. 

see opensmalltalk-vm/platforms/Mac OS/vm/Developer/sqMacMinimal.c, line 531

**Comment by krono** [comment]
Hey @pavel-krivanek, if you reference the fogbugz site, please at least include the gist of its discussion here. Fogbugz is a closed site and not everybody has an account there.,=

Also, can you tell _why_ `10 @ 10` is too small?
Why does a headless mode bother with the extent in the first place?

**Comment by pavel-krivanek** [comment]
The issue was described with this code
```bash
curl get.pharo.org/60+vm | bash
./pharo Pharo.image save 1.image
./pharo-ui 1.image
```
When you did it, the Pharo started but no UI was shown. Then we realized that the UI actually started and the window was opened but it was so small that it was hard to notice. 
So, when you start the image in headless mode, the VM during saving sets the real window size and since the headless VM has no window, it is set to fallback values (10@10).
Then when the image is started in standard mode with the display, it extremely small.

**Comment by pavel-krivanek** [comment]
I'm pretty sure it is a VM problem. For example on Linux it works as expected (which kind of supports that it is VM related). Mac does not take the display size from the Display but from the window, see the related method:
```c
int ioScreenSize(void) {
	/* return the screen size as two positive 16-bit integers packed into a 32-bit integer */
	int w = 10, h = 10;

	if (stWindow != nil) {
		w = stWindow->portRect.right - stWindow->portRect.left;
		h = stWindow->portRect.bottom - stWindow->portRect.top;
	}
	return (w << 16) | (h & 0xFFFF);  /* w is high 16 bits; h is low 16 bits */
}
```

**Comment by krono** [comment]
(note that `platforms/Mac OS/vm/Developer/sqMacMinimal.c` is no longer used, it is from the deprecated Carbon Mac VM)

**Comment by krono** [comment]
Ok, here's the roundup:

 1. Mac: seems to has ever used 10@10 as fallback, apparently since the 1990s ([fallback still](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/a8a1dc1e33267e0fa2dab22959e41d0a072420d9/platforms/iOS/vm/Common/Classes/sqSqueakNullScreenAndWindow.m#L70) ) 
    But sometimes returns `16@16` [when headless is detected](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/a8a1dc1e33267e0fa2dab22959e41d0a072420d9/platforms/iOS/vm/OSX/sqSqueakMainApplication%2Bscreen.m#L52)

 2. Windows: 
     - Tries window's size, if window is there
     - [Tries saved size (which comes from image)](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/e2fa2d10b4e85f1fae03f4e759527eb8e1742385/platforms/win32/vm/sqWin32Window.c#L1752)
    _However_, when setting the window size, it 
     - [Avoids doing that in headless mode](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/e2fa2d10b4e85f1fae03f4e759527eb8e1742385/platforms/win32/vm/sqWin32Window.c#L997)     
     - [Tries saved size (which comes from vm)](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/e2fa2d10b4e85f1fae03f4e759527eb8e1742385/platforms/win32/vm/sqWin32Window.c#L1000),
     - [Uses default of `640@480` (aka VGA)](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/e2fa2d10b4e85f1fae03f4e759527eb8e1742385/platforms/win32/vm/sqWin32Window.c#L1000)
     - [but makes sure that it's at least `64@64`](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/e2fa2d10b4e85f1fae03f4e759527eb8e1742385/platforms/win32/vm/sqWin32Window.c#L1007)

    Which means that one call to `SetWindowSize` makes everything even more inconsistent
 
 3. Unix: First note: reading the Screen size actually [_can change the physical screen size_](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/a8a1dc1e33267e0fa2dab22959e41d0a072420d9/platforms/unix/vm-display-X11/sqUnixX11.c#L4956)
    - [Starts from the images saved size (which comes from image)](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/a8a1dc1e33267e0fa2dab22959e41d0a072420d9/platforms/unix/vm-display-X11/sqUnixX11.c#L4935)
    - [In headless, gives that saved size](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/a8a1dc1e33267e0fa2dab22959e41d0a072420d9/platforms/unix/vm-display-X11/sqUnixX11.c#L4937) or, if that is not available, [just `64@64`](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/a8a1dc1e33267e0fa2dab22959e41d0a072420d9/platforms/unix/vm-display-X11/sqUnixX11.c#L4938)
     - Only then, after possible resizing of the physical window, the [actual size is determined](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/a8a1dc1e33267e0fa2dab22959e41d0a072420d9/platforms/unix/vm-display-X11/sqUnixX11.c#L4956)

----- 

_Nothing_ of this is consistent. The most common thing is to return the saved size or `64@64`.

The only thing to fix that here is to actually make the Cocoa VM query the image for its saved size, yes.
But save for that, I would avoid hardcoding like #289 .

**Comment by pavel-krivanek** [comment]
Thank you for the analysis. I will close that PR
