### ISSUE TITLE
Update README with load instructions : VMMaker in Squeak

### ISSUE THREAD

**Issue by ghost** [OpenSmalltalk/opensmalltalk-vm#294]
A user interested in generating VMs for Squeak, Pharo and Cuis needs to know how to load the source code.

Add instructions on how to do this in Squeak  - VMMaker load instructions. 
Use release 5.2.

**Comment by ghost** [comment]
Some instructions here

https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/e2fa2d10b4e85f1fae03f4e759527eb8e1742385/image/BuildSqueakSpurTrunkVMMakerImage.st

The question is what I need to do to load VMMaker given I have a Squeak 5.2 release image.

**Comment by eliotmiranda** [comment]
Hi,  the scripts around BuildSqueakSpurTrunkVMMakerImage.st are buildspurtrunkvmmaker[64]image.sh.  And instructions for that are here: [http://www.mirandabanda.org/cogblog/build-image/](http://www.mirandabanda.org/cogblog/build-image/)

**Comment by ghost** [comment]
I understand that I take a Squeak5.2 release image and run the following script to get a full VMMaker  image.

https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/image/BuildSqueakSpurTrunkVMMakerImage.st

**Comment by eliotmiranda** [comment]
Hi hjht,

    you repeated yourself.  Why? (just curious).  Was my comment unhelpful?  Where do you want the instructions to go?
