### ISSUE TITLE
Mac OS regression: freeze image with two-finger-scroll using touchpad

### ISSUE THREAD

**Issue by f4lco** [OpenSmalltalk/opensmalltalk-vm#302]
I reproducibly encounter image freezes using two-finger scroll on Mac OS using version

> 5.0 5.0.201810270242 Mac OS X built on Oct 27 2018 02:46:13 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31) [Production Spur 64-bit VM]
CoInterpreter VMMaker.oscog-eem.2461 uuid: b3cd33f5-6309-43a1-b669-7a1805111f34 Oct 27 2018
StackToRegisterMappingCogit VMMaker.oscog-eem.2464 uuid: 0b1fa0a3-a781-4fd5-b1cf-1809796ccbbf Oct 27 2018
VM: 201810270242 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
Date: Fri Oct 26 19:42:18 2018 CommitHash: df9064a
Plugins: 201810270242 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

when, however, the following version is fine:

> 5.0 5.0.201810190412 Mac OS X built on Oct 20 2018 08:16:09 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31) [Production Spur 64-bit VM]
CoInterpreter VMMaker.oscog-eem.2461 uuid: b3cd33f5-6309-43a1-b669-7a1805111f34 Oct 20 2018
StackToRegisterMappingCogit VMMaker.oscog-eem.2464 uuid: 0b1fa0a3-a781-4fd5-b1cf-1809796ccbbf Oct 20 2018
VM: 201810190412 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
Date: Thu Oct 18 21:12:21 2018 CommitHash: 15341b5
Plugins: 201810190412 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

I've attached a screencast of what I did. At first one can see that the image I opened is in principle functional, that is, window decoration lights up on mouse-over, list items highlight when hovered, and clicks on list items work as expected (screen recording tool adds extra highlight to clicks). All of this happens using an external mouse. Around the ten second mark I  switch to the MacBook touchpad and attempt a two-finger scroll. Suddenly all of the mentioned behaviors stop working, as if input was completely stalled. It is probably not a complete image freeze, because the frame counter still appears to be operational. However, I'm not even able to close the image using the red button.

![screen recording 2018-11-07 at 14 19 54](https://user-images.githubusercontent.com/29141485/48135100-36fb1400-e29c-11e8-88d7-2f8791592886.gif)

**Comment by guillep** [comment]
Hi @f4lco ,

Could you try with latest vm? Possibly this got fixed in https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/b6cb1927f39786de37d829a8677fe9cac2693a94

Tx,
Guille

**Comment by eliotmiranda** [comment]
And please report back ASAP if it works or not..

**Comment by f4lco** [comment]
Hello @guillep @eliotmiranda,

I cannot reproduce the behaviour given version:

> 5.0 5.0.201811061137 Mac OS X built on Nov  6 2018 11:42:17 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31) [Production Spur VM]
CoInterpreter VMMaker.oscog-eem.2461 uuid: b3cd33f5-6309-43a1-b669-7a1805111f34 Nov  6 2018
StackToRegisterMappingCogit VMMaker.oscog-eem.2461 uuid: b3cd33f5-6309-43a1-b669-7a1805111f34 Nov  6 2018
VM: 201811061137 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
Date: Tue Nov 6 03:37:05 2018 CommitHash: fe517ee
Plugins: 201811061137 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

It appears to be fixed 🙂 

It appears to be running smooth except for a little more log spam:

> /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'

Above is directly prepended to the version information when running with `-version`. Probably unrelated but I just wanted you to know.

**Comment by f4lco** [comment]
Apparently there are no further questions, problem is fixed. Thanks for your quick response on the issue. Keep up the good work!
