### ISSUE TITLE
Incomplete implementation of `asByteArray` for negative numbers?

### ISSUE THREAD

**Issue by maximvl** [OpenSmalltalk/opensmalltalk-vm#324]
Hi, I found this while implementing a binary protocol - negative numbers are encoded in the same way as positive:
```
10 asByteArray = (-10 asByteArray) .  " => true"
```
While (usually) that's not the case and `bitString` shows it as well:
```
10 bitString = (-10 bitString ).  " => false"
```

I suggest that `-10 asByteArray` result is same as bitstring represented in bytes, as well as `asByteArrayOfSize:`.

What do you think?

**Comment by maximvl** [comment]
The solution can be like this for `asByteArrayOfSize:` and `asByteArray` is pretty similar:
```
negative := self negative.
negative 
	ifTrue: [
		number := self + 1.
		answer := ByteArray new: aSize withAll: 255 ]
	ifFalse: [
                number := self.
		answer := ByteArray new: aSize. ].

digitPos := 1.
aSize 
	to: aSize - number digitLength + 1
	by: -1
	do: 
		[ :pos | 
		answer 
			at: pos
			put: (
				negative 
					ifTrue: [ 255 - (number digitAt: digitPos) ]
					ifFalse: [ number digitAt: digitPos ]
			).
		digitPos := digitPos + 1 ].
^ answer.
```

**Comment by maximvl** [comment]
Also `asInteger` of ByteArray should be changed accordingly to support negative numbers.

**Comment by smalltalking** [comment]
These methods only exist in one fork using the VM, and they are all unrelated to the VM itself.
You might want to close this issue and open another one on the fork's issue tracker.

**Comment by bencoman** [comment]
Which fork is that?

**Comment by smalltalking** [comment]
Pharo. But it's totally irrelevant, as this is repository is for the VM.

**Comment by maximvl** [comment]
@smalltalking Oh sorry, the Pharo project does not support issues on github, I thought I should put it here.

Do you know where can I report this?

**Comment by bencoman** [comment]
@maximvl, Go to [pharo.fogbugz.com](https://pharo.fogbugz.com)
