### ISSUE TITLE
Persistant broken build - products/phcogspurlinuxhtRPi No such file or directory

### ISSUE THREAD

**Issue by bencoman** [OpenSmalltalk/opensmalltalk-vm#333]
Opening investigation into persistent build failure present in [latest build](https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/builds/473863916)
```
1599.41  ARCH="linux32ARMv6"   FLAVOR="pharo.cog.spur" 
/usr/bin/find: `../../../products/phcogspurlinuxhtRPi': No such file or directory
The command "$CHROOT ./scripts/ci/travis_build.sh" failed and exited with 1 during .
```
Seems to have first failed 2018-12-28 in [build #1577](https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/builds/473004186) commit https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/968ed91bd
Last success was 2018-12-19 [build #1553](https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/builds/473004186) commit https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/96a866b17
The intervening commits are:    
```
$ git log --graph --pretty=format:"%h %ad %an - %s" --date=short   96a866b~1..968ed91
```

| 968ed91bd **[BAD]** 2018-12-28 Nicolas Cellier - Generate VM code from VMMaker.oscog-nice.2501
| 0ab0a27a1 **[GOOD]** 2018-12-24 Eliot Miranda - CogVM source as per VMMaker.oscog-eem.2498 [skip ci] no point building; this alters nothing that is currently built.
|   e14d4d63f **[GOOD]** 2018-12-21 akgrant43 - Merge pull request #328 from akgrant43/sortBinTray
|\\
| | a20975e3a 2018-12-21 AlistairGrant - getGoodSpur[64]VM.sh sort for latest VM
|/
|   7ab324c0e **[GOOD]** 2018-12-21 akgrant43 - Merge pull request #326 from shingarov/Cog  
|\\
| |   1015842be 2018-12-21 Boris Shingarov - Merge branch 'Cog' of shingarov/opensmalltalk-vm into Cog
| |\\
| | |   f57514792 2018-12-21 Boris Shingarov - Merge branch 'Cog' of shingarov/opensmalltalk-vm into Cog
| | |\\
| | | \\   f0818266c 2018-12-21 Boris Shingarov - Merge branch 'Cog' of shingarov/opensmalltalk-vm into Cog
| |\\ \\ \\
| | |/ /
| |/| /
| | |/
| | | aecc9e6ef 2018-12-21 Boris Shingarov - Check sanity of curled gzip data
| |/
|/|
| | a2bdae44d 2018-12-21 Boris Shingarov - Check sanity of curled gzip data
|/
| 5beee8f14 2018-12-20 Eliot Miranda - Document the [ci skip] trick/hack/bounty/miracle/undocumented, unobvious yet incredibly helful reducer of CO2 emissions in README.md.
| 96a866b17 **[GOOD]** 2018-12-19 Eliot Miranda - A link to the image directory ius more helpful.

**Comment by bencoman** [comment]
Side note, just noticed this command, maybe help compiling locally...
```
debootstrap --arch armhf --foreign --no-check-gpg --include=fakeroot,build-essential jessie /home/travis/build/bencoman/opensmalltalk-vm/armchroot http://archive.raspbian.org/raspbian
```

**Comment by bencoman** [comment]
Doing a recursive diff between 0ab0a27 and 968ed91 shows changes under only under \*src\* directories.

Searching on "failed" in a [diff of their respective build logs](https://www.diffchecker.com/amM9rEuu) (slightly massaged) shows...
```
1	issue333-first-bad-build-968ed91.log
5361	Makefile: : recipe for target 'cogit. o' failed
5362	make[1]: *** [cogit. o] Error 1
5363	Makefile: : recipe for target 'vm/vm. a' failed
5364	make: *** [vm/vm. a] Error 2
```

Searching on "error" leads to this...
```
home/travis/build/bencoman/opensmalltalk-vm/spursrc/vm/cogitARMv5.c:2300:2: error: void value not ignored as it ought to be
  return error("subclassResponsibility");
  ^
/home/travis/build/bencoman/opensmalltalk-vm/spursrc/vm/cogitARMv5.c: In function 'unalignedLongAtput':
/home/travis/build/bencoman/opensmalltalk-vm/spursrc/vm/cogitARMv5.c:2307:2: error: void value not ignored as it ought to be
  return error("subclassResponsibility");
  ^
/home/travis/build/bencoman/opensmalltalk-vm/spursrc/vm/cogitARMv5.c: In function 'callFullTargetFromReturnAddress':
/home/travis/build/bencoman/opensmalltalk-vm/spursrc/vm/cogitARMv5.c:2491:2: error: void value not ignored as it ought to be
  return error("subclassResponsibility");
  ^
```

Here are the original build logs...
Good: https://travis-ci.org/bencoman/opensmalltalk-vm/builds/474116732
Bad: https://travis-ci.org/bencoman/opensmalltalk-vm/builds/474118233

P.S. The `make -j4` made it awkward to compare logs between builds.  Had to remove that option.

**Comment by nicolas-cellier-aka-nice** [comment]
Since I only regenerated VM sources from VMMaker, and that sources are shared with Squeak/Newspeak, and that Squeak/Newspeak ARM builds success, I convinced myself that it was yet another infrastructure problem with PharoVM.

But if it's cogit.o that failed, then it would be interesting to inquire the diffs inside a #ifdef Pharo...
Err, but that would happen only in ARM, and not in X86/64?

Note that 0ab0a27 has [skip CI]

And  0ab0a27  has introduced ThreadedARM64FFIPlugin compatibility, which seems related...
It has modified this plugin src/plugins/SqueakFFIPrims/ARM32FFIPlugin.c
And pharo is the only flavour having the plugin built internal, see:

    $ grep SqueakFFI `find build.*ARM* -name 'plugins.???'`
    build.linux32ARMv6/pharo.cog.spur/plugins.int:SqueakFFIPrims \
    build.linux32ARMv6/squeak.stack.spur/plugins.ext:SqueakFFIPrims \
    build.linux32ARMv6/squeak.stack.v3/plugins.ext:SqueakFFIPrims \
    build.linux32ARMv6/squeak.cog.spur/plugins.ext:SqueakFFIPrims \
    build.linux64ARMv8/squeak.stack.spur/plugins.ext:SqueakFFIPrims \

Maybe it's a clue...

**Comment by bencoman** [comment]
[Diff of cogitARMv5.c](https://www.diffchecker.com/EqH3F37Y) between 0ab0a27 [GOOD]  and  968ed91 [BAD].
Its taken the day to isolate it this far.  Heading to bed now.  @akgrant, @nicolas-cellier-aka-nice, would you like to have a crack at determining a fix.

[EDIT: Individual files attached if a local diff tool is preferred (I find WinMerge pretty good)]
[cogitARMv5.zip](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/2719533/cogitARMv5.zip)

**Comment by bencoman** [comment]
>pharo is the only flavour having the plugin built internal

Good to know that may be why only Pharo is failing.

> Note that 0ab0a27 has [skip CI]

I've been building 0ab0a27 plus my culled travis.yml and its a GOOD build.  

The failure is definitely from 968ed91 introducing...
```
	/* CogAbstractInstruction>>#unalignedLongAt: */
static sqInt NoDbgRegParms
unalignedLongAt(AbstractInstruction * self_in_unalignedLongAt, sqInt byteAddress)
{
	return error("subclassResponsibility");
}

	/* CogAbstractInstruction>>#unalignedLongAt:put: */
static sqInt NoDbgRegParms
unalignedLongAtput(AbstractInstruction * self_in_unalignedLongAtput, sqInt byteAddress, sqInt aWord)
{
	return error("subclassResponsibility");
}
```
```
	/* CogARMCompiler>>#callFullTargetFromReturnAddress: */
static sqInt NoDbgRegParms
callFullTargetFromReturnAddress(AbstractInstruction * self_in_callFullTargetFromReturnAddress, sqInt callSiteReturnAddress)
{
	return error("subclassResponsibility");
}
```
There are no "Pharo" strings in the file.

**Comment by akgrant43** [comment]
Hi Nicolas,

Just adding to what Ben wrote above, the error from the compiler is:

```
In file included from /home/travis/build/OpenSmalltalk/opensmalltalk-vm/spursrc/vm/cogit.c:7:0:
/home/travis/build/OpenSmalltalk/opensmalltalk-vm/spursrc/vm/cogitARMv5.c: In function 'unalignedLongAt':
/home/travis/build/OpenSmalltalk/opensmalltalk-vm/spursrc/vm/cogitARMv5.c:2300:2: error: void value not ignored as it ought to be
  return error("subclassResponsibility");
  ^
```

**Comment by akgrant43** [comment]
Hmm, forget what I wrote above,  That code appears to have been removed in later commits (f954a91).

cogitXXXX.c generates LOTS of warnings, but appears to build.

Sorry for the noise.

**Comment by nicolas-cellier-aka-nice** [comment]
OK, I see it now, re-generating cogitARMv5.c adds the definition of unalignedLongAt.
The last generation was VMMaker.oscog-eem.2482, so a few things have happened in VMMaker in between, including code generation...
I'm not responsible for any stuff touching unalignedLongAt, but I should not have regenerated...
I wonder why squeak do succeed? Different compiler options?

Eliot has already fixed that in VMMaker.oscog-eem.2502 so as to <do not generate>:

    unalignedLongAt: byteAddress
	"Some processors need this, but word-oriented RISCs don't. Hence doNotGenerate."
	<doNotGenerate>
	^self subclassResponsibility

Either I revert, or I try to generate with 2502...

**EDIT**
OK, I cross-posted, Eliot did already re-generate indeed...

**Comment by nicolas-cellier-aka-nice** [comment]
Already fixed

**Comment by akgrant43** [comment]
> Already fixed

Are you sure?  https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/builds/474186755?utm_source=github_status&utm_medium=notification  is Cog (HEAD) with just the ARM platform and SqueakFFIPrims moved from plugins.int to plugins.ext.  The same error occurs in both squeak and pharo.

So the problem appears to be something else than SqueakFFIPrims.

But bed time...

**Comment by nicolas-cellier-aka-nice** [comment]
Sorry, I believed you when you told that cogitXXX was building OK, and it build OK.
But I did not verify anything else.

Still, there is a FFI problem, look in the console:

> libtool: compile:  gcc -std=gnu99 -g -O2 -fwrapv -DNDEBUG -DDEBUGVM=0 -DPharoVM -DI_REALLY_DONT_CARE_HOW_UNSAFE_THIS_IS -DUSE_MIDI_ALSA -DCOGMTVM=0 -Wall -pthread -DLSB_FIRST=1 -march=armv6 -mfpu=vfp -mfloat-abi=hard -Wno-missing-braces -Wno-unknown-pragmas -Wno-unused-value -Wno-unused-label -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -DHAVE_CONFIG_H -I/home/travis/build/OpenSmalltalk/opensmalltalk-vm/build.linux32ARMv6/pharo.cog.spur/build -I/home/travis/build/OpenSmalltalk/opensmalltalk-vm/build.linux32ARMv6/pharo.cog.spur/build -I/home/travis/build/OpenSmalltalk/opensmalltalk-vm/platforms/unix/vm -I/home/travis/build/OpenSmalltalk/opensmalltalk-vm/platforms/Cross/vm -I/home/travis/build/OpenSmalltalk/opensmalltalk-vm/spursrc/vm -I/usr/local/include -I/home/travis/build/OpenSmalltalk/opensmalltalk-vm/platforms/Cross/plugins/SqueakFFIPrims -I/home/travis/build/OpenSmalltalk/opensmalltalk-vm/platforms/unix/plugins/SqueakFFIPrims -march=armv6 -mfpu=vfp -mfloat-abi=hard -Wno-missing-braces -Wno-unknown-pragmas -Wno-unused-value -Wno-unused-label -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -c /home/travis/build/OpenSmalltalk/opensmalltalk-vm/src/plugins/SqueakFFIPrims/SqueakFFIPrims.c  -fPIC -DPIC -o .libs/SqueakFFIPrims.o
> /home/travis/build/OpenSmalltalk/opensmalltalk-vm/src/plugins/SqueakFFIPrims/SqueakFFIPrims.c:31:3: error: #error As yet no FFI implementation appears to exist for your platform.
>  # error As yet no FFI implementation appears to exist for your platform.
>    ^
> /home/travis/build/OpenSmalltalk/opensmalltalk-vm/src/plugins/SqueakFFIPrims/SqueakFFIPrims.c:32:3: error: #error Consider implementing it, starting by adding a subclass of ThreadedFFIPlugin.
>  # error Consider implementing it, starting by adding a subclass of ThreadedFFIPlugin.
>    ^

This happens for Pharo build and in the Squeak build too.
But only Pharo then later fails.
It builds vm.a OK, but fails somewhere later. 
The exact error is:

> libtool: link: ar cru .libs/JPEGReadWriter2Plugin.a  JPEGReadWriter2Plugin.o Error.o jcapimin.o jcapistd.o jccoefct.o jccolor.o jcdctmgr.o jchuff.o jcinit.o jcmainct.o jcmarker.o jcmaster.o jcomapi.o jcparam.o jcphuff.o jcprepct.o jcsample.o jctrans.o jdapimin.o jdapistd.o jdatadst.o jdatasrc.o jdcoefct.o jdcolor.o jddctmgr.o jdhuff.o jdinput.o jdmainct.o jdmarker.o jdmaster.o jdmerge.o jdphuff.o jdpostct.o jdsample.o jdtrans.o jerror.o jfdctflt.o jfdctfst.o jfdctint.o jidctflt.o jidctfst.o jidctint.o jidctred.o jmemdatadst.o jmemdatasrc.o jmemmgr.o jmemnobs.o jquant1.o jquant2.o jutils.o sqJPEGReadWriter2Plugin.o
> libtool: link: ranlib .libs/JPEGReadWriter2Plugin.a
> libtool: link: ( cd ".libs" && rm -f "JPEGReadWriter2Plugin.la" && ln -s "../JPEGReadWriter2Plugin.la" "JPEGReadWriter2Plugin.la" )
> : JPEGReadWriter2Plugin.la
> /usr/bin/find: `../../../products/phcogspurlinuxhtRPi': No such file or directory

bed time too...
reading those consoles and trying to guess  is exhausting

**Comment by nicolas-cellier-aka-nice** [comment]
So,
- I generated code from VMMaker.oscog-2501, which introduced a code generation bug from an earlier VMMaker version (unalignedLongAt)
- Eliot soon corrected the problem in VMMaker.oscog-2502, which fixed the unalignedLong, but introduced another problem in SqueakFFIPrims (there is no more `if defined(__arm__)` in the new code).

I would say, we can make mistakes, but it will be a lot lot easier to correct if we decompose the modifications!
One feature, one commit.

**Comment by akgrant43** [comment]
Further investigation in https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/334

**Comment by nicolas-cellier-aka-nice** [comment]
Fixed in https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/1c6552daac9cc823b3a74b643676b3a346f0bf5d
