### ISSUE TITLE
getRMCC() macro should not take an argument

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [OpenSmalltalk/opensmalltalk-vm#342]
This macro is used in threaded FFI
https://github.com/OpenSmalltalk/opensmalltalk-vm/search?q=getRMCC&unscoped_q=getRMCC

BTW, it is Recent Most Callback Context, or MRCC?

I open the issue so as to not forget to come back to it later...

**Comment by eliotmiranda** [comment]
Oops.  That should indeed be getMRCC and setMRCC(t).  I shall fix it now...

**Comment by eliotmiranda** [comment]
Fixed by commit a8a5eb673d3ea51d76802aed31719e7bbe0687f0

**Comment by nicolas-cellier-aka-nice** [comment]
Fixed in a8a5eb673d3ea51d76802aed31719e7bbe0687f0
