### ISSUE TITLE
Win32 builds are failing

### ISSUE THREAD

**Issue by timfel** [OpenSmalltalk/opensmalltalk-vm#35]
It seems our appveyor script has problems reporting the exit status of the build. These all seem to be failing: https://ci.appveyor.com/project/OpenSmalltalk/vm/build/1.0.164

**Comment by krono** [comment]
thanks. thats really strange

**Comment by krono** [comment]
(not yet fixed: https://ci.appveyor.com/project/OpenSmalltalk/vm/build/1.0.171/job/sv5o8totj7nda08i)

**Comment by nicolas-cellier-aka-nice** [comment]
Hi both, Can we close this one?
