### ISSUE TITLE
Remove PharoV50.sources from pharo builds

### ISSUE THREAD

**Issue by akgrant43** [OpenSmalltalk/opensmalltalk-vm#365]
Pharo generates the sources file for each image, so there's no point shipping an out-of-date sources file with the VM.

Thanks to Hilaire for the initial report, see http://forum.world.st/PharoV50-sources-in-VM-td5094603.html

I'll submit a PR soon(ish).

**Comment by fniephaus** [comment]
AFAICT, the Pharo VMs in our releases tab do not come with that outdated sources file. Otherwise they would be much larger in size. So I'm assuming this is a Pharo-specific packaging problem.

**Comment by akgrant43** [comment]
Hi Fabio,

If I download https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/download/201901172323/pharo.cog.spur_linux64x64_201901172323.tar.gz

then:

$ tar tzvf pharo.cog.spur_linux64x64_201901172323.tar.gz | grep sources
-rw-rw-r-- travis/travis 6446328 2017-05-18 17:48 phcogspur64linuxht/lib/pharo/5.0-201901172323/PharoV50.sources

For linux it's added in editpharoinstall.sh.

**Comment by fniephaus** [comment]
Oh, that's right...I didn't notice that some files are 12-13MB...we should change that if not needed at all! Thanks

**Comment by akgrant43** [comment]
Resolved by #366
