### ISSUE TITLE
Deleting a directory on a CIFS mounted file system fails

### ISSUE THREAD

**Issue by akgrant43** [OpenSmalltalk/opensmalltalk-vm#368]
As reported by Albrecht, deleting a directory on a cifs mounted drive results in a DirectoryIsNotEmpty exception being incorrectly raised.

See: http://forum.world.st/Why-DirectoryIsNotEmpty-on-FileReference-gt-gt-deleteAll-td5094589.html

The problem can be reproduced with:

```smalltalk
| root sourceFolder deleteMeFolder numberOfRetries | 

root := '/path/to/cifs/mount' asFileReference.
sourceFolder := root / 'src'.
sourceFolder ensureCreateDirectory.
(sourceFolder / 'empty.file') ensureCreateFile. 
deleteMeFolder := root / 'delme'. 

"copy sourceFolder to deleteMeFolder:" 
sourceFolder copyAllTo: deleteMeFolder. 

"delete deleteMeFolder again:" 
numberOfRetries := 0. 
[    deleteMeFolder asFileReference deleteAll ] on: DirectoryIsNotEmpty 
do: [ :ex | 
	self halt.
     (numberOfRetries := numberOfRetries + 1) < 5 
         ifTrue: [ ex retry ]    ]. 
Transcript crLog . 
Transcript show: 'Retries: ', numberOfRetries asString . 
```

Then execute:

```
$ sudo lsof | grep delme
$ ls /path/to/cifs/mount
```

and you'll see the deleted entries are still held open by the VM and delme still exists in the parent directory (root above).

**Comment by a2b-alb** [comment]
Details on VM and image version from system reporter:

Image:
Pharo7.0.1
Build information: Pharo-7.0.1+build.142.sha.b8825954d0dcff883bf4f47ea5c516c9cfc2fe4b (64 Bit)

Virtual Machine:
/pharo-vm/lib/pharo/5.0-201901051900/pharo
CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
VM: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b64 Plugins: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

Unix built on Jan  5 2019 19:12:23 Compiler: 4.8.4
VMMaker versionString VM: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b64 Plugins: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019

**Comment by akgrant43** [comment]
Albrecht, thanks for the system info.

PR: https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/371

**Comment by akgrant43** [comment]
Fixed confirmed by Albrecht, commit https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/a838346b1a67712cc28298534dafbd0c26ea34fb
