### ISSUE TITLE
"r" in Version string

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#37]
AFAIK, we agreed on this version number format: `YYYYMMDDHHSS`.
Inside an image, the VM reports a version like `r201608141014`. Shall we remove the `r` here in order to make it consistent?

[Related code](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/0629281c720d36c86d5014a3b9af2e95239e053e/platforms/Cross/vm/sqSCCSVersion.h#L120).

**Comment by eliotmiranda** [comment]
done.
