### ISSUE TITLE
Add support for retina displays

### ISSUE THREAD

**Issue by ad-si** [OpenSmalltalk/opensmalltalk-vm#378]
I just installed Pharo & Squeak and my first impression is rather bad. Nothing screams ancient / unmaintained / not production ready / shitty like no support for retina displays. It has been 6 years since retina displays were released and they should really be supported by now.

This has been listed on https://github.com/pharo-project/pharo-workingRoadmaps/blob/master/Pharo7/ROADMAP.md#vm for quite a few years, but apparently nothing has happened yet. From a user standpoint this should be of really high priority in my opinion.

Sorry for popping up here and criticising. Just wanted to provide my experience.

**Comment by bencoman** [comment]
@estebanlm Is this something that might be helped using minheadless for Pharo 8 ?

**Comment by fniephaus** [comment]
I understand your frustration, @ad-si. Squeak has a high-res/demo mode that somewhat works on Windows when auto-upscaling is disabled. But none of the release VMs support it officially. There's a branch for adding high-res support, but development has stalled at some point unfortunately. Maybe @krono can provide a quick status update? The Pharo community is currently working on Bloc which is supposed to provide high-res graphics I think.

**Comment by ad-si** [comment]
Putting my money where my mouth is:
I'm adding a 50€ bounty if it get's implemented until end of May for MacOS 😁

**Comment by krono** [comment]
[Squeak64_201706232142-highdpi-v2.app.zip](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/2999560/Squeak64_201706232142-highdpi-v2.app.zip)

You can drop by my office if you want to…

**Comment by ad-si** [comment]
<img width="664" alt="Screen Shot 2019-03-23 at 16 40 55Z" src="https://user-images.githubusercontent.com/36796532/54868994-88f39080-4d8a-11e9-9ddc-e0104c6f7fc3.png">
Well … if now the device and app pixels would have a more favorable ratio 😉.
… but the point isn't about getting it running for me, but to get it into the stable release. I'd really like to be able to direct other developers to Squeak / Pharo as an example of how software development / IDEs should be done, but at the moment it's rather embarrassing.

What's the progress on this?

**Comment by fniephaus** [comment]
@ad-si: I think all you need to do now is to enable high-dpi mode (via World Menu > `appearance` > `system fonts` > `demo/hi-dpi mode`).

**Comment by bencoman** [comment]
On Sun, 24 Mar 2019 at 00:45, Adrian Sieber <notifications@github.com>
wrote:

> but the point isn't about getting it running for me, but to get it into
> the stable release.


Hi Adrian,

I hope someone takes you up on the challenge - not just for the money, but
because you stand you're taking for the community.

cheers -ben

>

**Comment by ad-si** [comment]
@fniephaus @krono
Ah cool, thanks. Kind of works! I mean the graphics should be changed as well and not just the fonts, but this makes it already way better.
So what's stopping you from merging it upstreams?

**Comment by krono** [comment]
Because I have alreay invested more than a month's time and it turns out, getting it right is actually hard.
You only saw a third of the things necessary to make it work right.

Think cross-platform, think multi-monitor, think changing tech (osx uses metal now).

Its not doable atm.
