### ISSUE TITLE
32-bit libB3DAcceleratorPlugin.dylib fails to link; 32-bit Squeak B3DAcceleratorPlugin links against metal.

### ISSUE THREAD

**Issue by eliotmiranda** [OpenSmalltalk/opensmalltalk-vm#385]
Seems to be something strange with the B3DAcceleratorPlugin on 32-bit macos.  The pharo libB3DAcceleratorPlugin.dylib fails to link missing:
  createOpenGLTextureLayerHandle
  destroyOpenGLTextureLayerHandle
  getMainWindowOpenGLContext
  setOpenGLTextureLayerContent

The Squeak one links, but apparently against Metal, which isn't going to work since Metal is 64-bit only (or so I've been told).

**Comment by nicolas-cellier-aka-nice** [comment]
I think that this can be closed because fixed by Ronie.
