### ISSUE TITLE
macOS Sierra Support

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#39]
Apparently, the OpenSmalltalk VMs do not run on MacOS Sierra betas yet:
http://forum.world.st/Re-ANN-Squeak-5-1-Code-Freeze-Trunk-still-closed-first-release-candidate-s-available-tp4911781.html

**Comment by marceltaeumel** [comment]
"[...]  They start but no Mac windows are displayed. [...]"

**Comment by StephanEggermont** [comment]
See Benjamin Pollack's Pull Request # 107 on the pharo vm site

**Comment by fniephaus** [comment]
For convenience, here's the link: https://github.com/pharo-project/pharo-vm/pull/107

**Comment by fniephaus** [comment]
Could someone on macOS Sierra verify if https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/f2b5cf27f81e50c65537972a89ddee9e0aac39c2 fixes the display problem? The latest build artifacts are [here](https://bintray.com/opensmalltalk/vm/cog/_latestVersion#files).

**Comment by edoneel** [comment]
Yes!  It works perfectly.  Thanks very very much!
