### ISSUE TITLE
Image buffer corruption when running build.macos64x64 targets

### ISSUE THREAD

**Issue by CogMachines** [OpenSmalltalk/opensmalltalk-vm#392]
Building from the latest sources on the Cog branch, I see the attached image when loading various images using various OSX builds. I have tried the 64-bit  Pharo, Squeak and newspeak builds with their associated images. I see some variation of the attached image below. If I rollback the source to the 201901172323 tag, I am able to build and load an image and see the window as expected. 

Using XCode 10.2.1 on OSX 10.14.3

<img width="811" alt="Screen Shot 2019-04-23 at 6 47 51 PM" src="https://user-images.githubusercontent.com/32800969/56627814-3fea6280-65fc-11e9-8bb0-e836cbf44187.png">

**Comment by eliotmiranda** [comment]
Hi Gene,

    Ronie can give you the details but this is due to his refactoring of the Mac graphics system to use Metal.  Currently we can’t get it to work correctly on older versions of MacOS.  Hopefully this is temporary.  You can select the older graphics subsysyems by using either of these as the first argument to the VM on the command line:
 -opengl
 -core-graphics

_,,,^..^,,,_ (phone)

**Comment by CogMachines** [comment]
When I reported the issue, I was running 10.14.3, not realizing I was a dot release behind. Even after upgrading to 10.14.4, I still see the issue. When you say older versions of MacOs, which version are  you developing for?

**Comment by nicolas-cellier-aka-nice** [comment]
I'm closing this one, because Ronie did the right thing since then.
If someone disagree, please raise your voice.
