### ISSUE TITLE
32-bit macOS CI builds broken due to new Metal integration

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#397]
It looks like the new Metal integration is not (yet) 32-bit compatible. Maybe we should use the old integration for 32-bit builds or nuke 32-bit builds for macOS completely (Apple is removing 32-bit support soon anyway).

Example: https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/jobs/538780335

**Comment by fniephaus** [comment]
Nonetheless, deployment of 64-bit bundles also seems to be broken at the moment for some reason.

See https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/jobs/538780337

**Comment by nicolas-cellier-aka-nice** [comment]
I provided a hack_to_restore_b3D_macos32x86 branch if ever we want to be able to deliver a final 32bits version on MacOS...

https://github.com/OpenSmalltalk/opensmalltalk-vm/tree/hack_to_restore_b3D_macos32x86
