### ISSUE TITLE
HostWindowPlugin does not account for window decorations on resize

### ISSUE THREAD

**Issue by marceltaeumel** [OpenSmalltalk/opensmalltalk-vm#40]
VM: 201608171728 (Cog, Spur)
HostWindowPlugin: VMMaker.oscog-eem.1716 (i)
Platform: Windows 10 1607, OS X El Capitan 10.11.6

If you call the named primitive `primitiveHostWindowSizeSet`, the Display will not have the correct size after the call.

Try it in Squeak 5.1rc1:

``` Smalltalk
DisplayScreen
   hostWindowExtent: 800@600;
   checkForNewScreenSize.
self assert: Project current world extent = (800@600).
```

In Squeak, there is a image-side workaround for that in `DisplayScreen >> #setNewScreenSize:`, which calculates the difference and then calls the primitive again.

**On OS X** the bug seems to affect only the window title bar and hence only the height. **On Windows 10** also the left/right shadows interfere and hence both height and width are wrong.

This bug affects both the 32-bit and the 64-bit versions.

**Comment by eliotmiranda** [comment]
I finally fixed this in d990bfd62542194ccc86b9687c7c1d9636a66403
