### ISSUE TITLE
Support for OpenBSD

### ISSUE THREAD

**Issue by asarch** [OpenSmalltalk/opensmalltalk-vm#413]
Is it possible to build OpenSmalltalk VM for OpenBSD?

If yes, how? If no, is there any other solution available?

OpenBSD ports for 6.4 for AMD64 has only the 3.10-1 version available.

**Comment by bencoman** [comment]
I haven't worked with building the VM on OpenBSD, but I see this past discussions...
http://forum.world.st/Squeak-on-OpenBSD-td4945634.html
http://forum.world.st/Why-the-hell-directives-for-compiling-with-clang-were-not-taken-into-account-td5072444i20.html#a5073221

So there seem two places to review...
https://github.com/OpenSmalltalk/opensmalltalk-vm/compare/c1790b37...krono/openbsd
https://github.com/aryler/ostoobsd

Now it would be really great if you could create folders **build.openbsd32x86** and **build.openbsd64x64** to work in to merge the stuff the two urls above - to make it easier for the next person.

If files/folders need to be organised into a particularly way for OpenBSD Ports, it would be good to have a script to do that to convert from the standard opensmalltalk-vm folder arrangement.

**Comment by krono** [comment]
Hey

the Cog branch should build on OpenBSD.
If not, ping me.

No need to make a dedicated openbsd folder, just use the linux one(s).

Note that the VM is _not_ w^x compatible, nor mapstack, neither unveil.

**Comment by bencoman** [comment]
I wont push this point, but just to share a thought... One benefit of a dedicated folder is that it "advertises" the availability of a OpenBSD.  It helps potential users "feel" more confident about trying it.  There will be a percentage of people who came looking, didn't see any reference and just moved on without asking. 

If you don't want separate folders for Free/Net/Open-BSD, perhaps a **build.bsd64x64** folder would be appropriate?

**Comment by krono** [comment]
well, it even could be unix bla
but that is a whole different story.

Maybe have a different issue for that?

**Comment by asarch** [comment]
Can you do the build scripts less Bash? Or even better, can you use Makefiles for that?

**Comment by krono** [comment]
I understand your point.

We've had a lot of discussing about the whole build infrastructure and as it stands, it currently works for all the major dists we can support; moreover at the moment we have to focus on other parts of the VM. 

That means that the build infra (directories, bash, etc) will stay as is until we have enough manpower and consesus to find a more universal solution.

That being said, opensmalltalk-vm works and compiles on OpenBSD.
Yes it needs ports, but I think especiallt @ckeen can give some pointers on how to do things efficiently around that parts.

If anyone steps up making an upgrade to the port, all PRs are welcome.

**Comment by asarch** [comment]
Take a look:

[output.log](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/3474660/output.log)

**Comment by krono** [comment]
@asarch I have re-run your build on OpenBSD 6.4 and cannot reproduce.

Btw, do you really want to build a newspeak VM? I suggest starting with a plain squeak vm, which would mean starting ins

    opensmalltalk-vm/build.linux64x64/squeak.cog.spur/build

Also, make sure that you run squeak on a `w^x`-_disabled_ mount, otherwise it won't start (that's what's happening, I think):
```shell
# mount
/dev/sd0a on / type ffs (local, wxallowed)
```

**Comment by asarch** [comment]
Does it need to be root for compilation?

[output.log](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/3483925/output.log)


Here is my `/etc/fstab`:

```
63a90b947a6cabb5.b none swap sw
#63a90b947a6cabb5.a / ffs rw,softdep,wxallowed 1 1
63a90b947a6cabb5.a / ffs rw,softdep 1 1
63a90b947a6cabb5.d /home ffs rw,softdep,nodev,nosuid 1 2
```

The mounted partitions:

```
$ mount
/dev/sd0a on / type ffs (local, softdep)
/dev/sd0d on /home type ffs (local, nodev, nosuid, softdep)
```

What's wrong?

**Comment by krono** [comment]
It is missing `wxallowed` as in the commented line.

OpenSmalltalk-VM needs wxallowed to run, at the moment.

**Comment by asarch** [comment]
Ok, after doing a `dd if=/dev/zero of=/dev/rsd0c bs=1m count=1` by mistake in order to create a **vnconfig** device for compilation and restoring the entire system, I have:

[output.log](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/3489145/output.log)

So, I used the **Squeak5.2-18229-64bit.image**, **Squeak5.2-18229-64bit.changes** and **SqueakV50.sources** from **http://squeak.org/** and this is what I have now:

![Screenshot from 2019-08-10 12-23-06](https://user-images.githubusercontent.com/906401/62824967-e89bde00-bb69-11e9-9857-0b4ad6f75a3f.png)

One last question: how do you install it?

**Comment by ckeen** [comment]
* asarch <notifications@github.com> [190810 19:26]:
> Ok, after doing a `dd if=/dev/zero of=/dev/rsd0c bs=1m count=1` by mistake in order to create a **vnconfig** device for compilation and restoring the entire system, I have:
> 
> [output.log](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/3489145/output.log)
> 
> So, If used the Squeak5.2-18229-64bit.image, Squeak5.2-18229-64bit.changes and SqueakV50.sources from **http://squeak.org/** and this is what I have now:
> 
> ![Screenshot from 2019-08-10 12-23-06](https://user-images.githubusercontent.com/906401/62824967-e89bde00-bb69-11e9-9857-0b4ad6f75a3f.png)
> 
> One last question: how do you install it?


I have the repo in /usr/local/smalltalk. You should need to copy
the respective product/ subdir to a place with the wxallowed bit
set.

I do keep the whole git repo there though and occasionally update
and set my PATH accordingly.

You could have a look at the outdated squeak port for inspiration
on the proper install locations but IDK whether that's worth the
hassle tbh.

Kind regards,

Christian

-- 
May you be peaceful, may you live in safety, may you be free from
suffering, and may you live with ease.

**Comment by asarch** [comment]
Thank you!

Thank you very much for all guys.

**Comment by krono** [comment]
@asarch Great to see it working for you.
Sorry for your borked installation, tho :/

**Comment by asarch** [comment]
On the contrary, thank you, thank you very much for your patience and your time. Thank you.

P.S.

Just one last issue if I may, how would you compile the image from sources?:

http://files.squeak.org/sources_files/SqueakV50.sources.gz

**Comment by asarch** [comment]
> _Dave Ungar pointed out many years ago that Smalltalk is saved but not born again._

Nice quote.

**Comment by ccrraaiigg** [comment]
Norbert writes:

> Pharo since version 7.0 is bootstrapped on every build. And it is surely the best way to get a
> reliable artifact.

The approach you cited uses a plethora of external tools processing source code. That's composition, but not bootstrapping (something building itself, or "pulling itself up by its own bootstraps").

Whether you consider the essence of the system to reside in that source code or in machine instructions, reliability comes from being able to explain why each bit in the resulting artifact is there. I think that process is most understandable, and most effectively verified, when the space of those external tools is smallest. This is why I prefer systems that actually do bootstrap.

-C

**Comment by krono** [comment]
This thread, while quite interesing, is going off-topic.

I invite you all to continue the discussion over at [vm-dev](http://lists.squeakfoundation.org/mailman/listinfo/vm-dev) (or its [nabble mirror](http://forum.world.st/Squeak-VM-f104410.html)).

**Comment by noha** [comment]
Argh, that is what I thought I did. I‘m getting old 😀

**Comment by krono** [comment]
No problem. All issues here are mirrored at vm-dev.
But lets focus on issues present here at github and keep the general discussion over at vm-dev.
