### ISSUE TITLE
Pharo in OpenBSD

### ISSUE THREAD

**Issue by asarch** [OpenSmalltalk/opensmalltalk-vm#414]
Using **squeak.cog.spur** I get:

[pharo.log](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/3504466/pharo.log)

![Screenshot from 2019-08-14 19-41-15](https://user-images.githubusercontent.com/906401/63076137-d1f2df80-bef9-11e9-899c-67b32ccb29c8.png)

and building **pharo.cog.spur** I get:

[output.log](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/3504469/output.log)

**Comment by krono** [comment]
Pharo uses a lot of third-party libraries.

Most of these are not built when making `squeak.cog.spur`. This is known and not an error.

When compiling the pharo-specific VM, these libs (in this case SDL2) are either not prepared to be made with BSD `make` or flat out are not available on (Open)BSD.

**Comment by asarch** [comment]
Oh... :'-(

**Comment by krono** [comment]
Maybe someone from Pharo's VM people can chime in here. @estebanlm , for example?

**Comment by guillep** [comment]
Looks like
1) the openbsd build does not define the primitive `primitiveGetCurrentWorkingDirectory` (see `OSPlatform>>currentWorkingDirectoryPathWithBuffer:`)
2) as a fallback, Pharo tries to get the working directory using `libc`'s `getcwd` through FFI, yes, which is in Pharo asking for `'libc.so.6'`. Which version of `libc` do you have installed in your system?

Maybe for `getcwd` which is pretty standard we can not depend on `libc.so.6` but `libc.so`?
