### ISSUE TITLE
pharo x64 libssh2 crashes on Windows 1903

### ISSUE THREAD

**Issue by peteruhnak** [OpenSmalltalk/opensmalltalk-vm#416]
Since Windows 1903 update (which is now being rolled out), Pharo VM crashes on `libssh2-1.dll`.

Tested on P7 and P8 64bit with their respective VMs.
32bit seems to work.

Easiest way to reproduce is to try to fetch git repository over ssh, e.g.

```
Metacello new
	baseline: 'FileDialog';
	repository: 'github://pharo-contributions/file-dialog/repository';
	load.
```

This issue makes it impossible to use git over ssh.  (Switching to https does work as a temporary workaround.)

Windows crash log event:

```
Faulting application name: Pharo.exe, version: 5.0.0.0, time stamp: 0x00000000
Faulting module name: libssh2-1.dll, version: 0.0.0.0, time stamp: 0xaec0ae70
Exception code: 0xc0000005
Fault offset: 0x000000000001e6cb
Faulting process id: 0x2c8
Faulting application start time: 0x01d5577ece35e5f5
Faulting application path: C:\Users\uhnak\Documents\Pharo\vms\80-x64\Pharo.exe
Faulting module path: C:\Users\uhnak\Documents\Pharo\vms\80-x64\libssh2-1.dll
Report Id: 60cbf9ad-b7a2-4f48-9831-e2cbc80e7734
Faulting package full name: 
Faulting package-relative application ID: 
```

Is there a particular reason why we still use libssh2 1.7.0 (released 3 years ago), instead of a more recent one? https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/third-party/libssh2.spec

Dtto for libgit2 (0.25.1 released Jan 2017)
https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/third-party/libgit2.spec

Likely OpenSSL will also need to be updated as it is dependency of libssh2 https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/third-party/openssl.spec
Note that the current `1.0.2 LTS` ends at the end of the year and is replaced by `1.1.1 LTS` (until 2023 - https://www.openssl.org/policies/releasestrat.html )

I have also noticed that the Windows libssh Makefile doesn't contain code to download/unpack sources, unlike Linux and Mac

https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/build.win64x64/third-party/Makefile.libssh2
https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/build.linux64x64/third-party/Makefile.libssh2
https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/build.macos64x64/third-party/Makefile.libssh2

**Comment by fuhrmanator** [comment]
This bug bit me today on a new windows 10 machine. The worst is that there's zero feedback in the UI. I suppose it's a VM issue, but it's one of those things that will demotivate Pharo newcomers who don't know to look in a windows crash log.

**Comment by LTangaF** [comment]
I worked around this by replacing the libssh2-1.dll with the one from the Pharo 8.0 (64-bit) VM.

**Comment by krono** [comment]
@peteruhnak  is this still a problem?

**Comment by peteruhnak** [comment]
It was fixed in the pharo fork, but I don't know if that was merged back here; Unfortunately I use Pharo only to a limited extent these days. Feel free to close the issue.
