### ISSUE TITLE
Mixed SmallInteger/Float comparison is inexact in Spur64 when jitted

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [OpenSmalltalk/opensmalltalk-vm#417]
Comparison of SmallInteger and Float is simple in Spur32, we just have to convert the SmallInteger to a (double), which is an exact operation, and perform the comparison of (double).

But it's more tricky in Spur64 because SmallInteger has more precision (61 bits) than Float (53 bits) and thus conversion to (double) might be inexact...

Example:

	si := 1<<(Float precision + 2)+1.
	sf := si asFloat.
	self deny: sf = si.
	self deny: si = sf.

It's not obvious to find where the trick happens in the VM, because all code at upper level is equivalent to trivial asFloat conversion followed by comparison, and there are many possible path!

Let's concentrate on <=

SmallInteger receiver:
   - #primitiveLessOrEqual
   - #genPrimitiveLessOrEqual (JIT)
BoxedFloat64 receiver:
   - #primitiveFloatLessOrEqual
   - #genPrimitiveFloatLessOrEqual (JIT)
SmallFloat64 receiver:
   - #primitiveSmallFloatLessOrEqual
   - #genPrimitiveSmallFloatLessOrEqual (JIT)
All receivers (non jitted sender or stack VM only?):
   - #bytecodePrimLessOrEqual

For generated C code, the protection is programmed in lower level #loadFloatOrIntFrom:

To check that it does not exceed 53 bits, we shift the integer left << and forth >> and verify integrity. If not, we fail the primitive.
With shift length as programmed currently, the primitive will fail for 52 bits and above. It should fail for 54 bits and above, but that's a detail, the primitive will fail more often than necessary...

The problem is that there is no such exactness check for jitted primitives!

I have sketched a solution in Squeak inbox (See http://source.squeak.org/inbox/Kernel-nice.1260.diff), demonstrated here for SmallInteger <=

    ^(asFloat := self asFloat) = aNumber
         ifTrue: [self <= aNumber truncated]
         ifFalse: [asFloat <= aNumber]

In C code that is:

    if ( (double) si == sf ) return si <= (int64) sf;
    else return (double) si <= sf;

It works for all the comparisons (though = and ~= could be a bit simpler, no need to perform the comparison twice).

And it's simple enough to be jitted (I have prototyped it this evening).

**Comment by nicolas-cellier-aka-nice** [comment]
Hi David,
sort of... 

We know that `smallInt asFloat` may be inexact.
We could test whether it is exact or not with `smallInt asFloat asInteger = smallInt` like what is done in Squeak `SmallInteger>>#isAnExactFloat` check, but that's not what we do here.
What we do is to check if ever that rounding error could change the result of comparison. If it could not, then the rounding error is innocuous and we can proceed with float comparison.

So more exactly, the algorithm is:
- check if there is a possible ambiguity
- if yes, use exact comparison (the usual image side `smallInt <= smallFloat asTrueFraction`)
- if no, use inexact but innocuous comparison (the simple `smallInt asFloat <= smallFloat`)
  (strictly speaking, the comparison is exact, only the operands may not)

If `smallInt asFloat > smallFloat` we know for sure that `smallInt > smallFloat`.
If `smallInt asFloat < smallFloat` we know for sure that `smallInt < smallFloat`.
The only case where we could have ambiguity is when `smallInt asFloat = smallFloat`.

But in this case, we know that smallFloat value is integer. Indeed, either asFloat is exact, and `smallInt = smallFloat`, or inexact, but that means that `smallInt > (2 raisedTo: Float precision)` and then Float has not enough precision to have a fraction part. Thus `smallFloat asTrueFraction = smallFloat asInteger` in this ambiguous case, a nice thing for the VM to not deal with Fraction!

A potential remaining problem could be that smallFloat asInteger may be a LargeInteger, for example `SmallInteger maxVal asInteger > SmallInteger maxVal` in 64 bits image.
But we know that:
`SmallInteger minVal <= smallFloat and: [smallFloat <= SmallInteger maxVal nextPowerOfTwo]`
Thus in the VM, we are safe, SmallInteger span only 61 bits and we have 64 bits registers.

**Comment by nicolas-cellier-aka-nice** [comment]
Solved, I added more exahaustive tests in Squeak and they now pass
Never mind the CI failures... We really fail at keeping something so complex stable... way too many configurations!!!

**Comment by nicolas-cellier-aka-nice** [comment]
Just for archeology, the problem was foreseen in 2014 and fixed for non jitted code only
See thread
**[Vm-dev] Potential problems with 64bit spur large SmallInteger comparison**
http://lists.squeakfoundation.org/pipermail/vm-dev/2014-December/017401.html

Of course, it seems that google does not index that...

**Comment by eliotmiranda** [comment]
Hi Nicolas,

    I apologize for not having noticed this issue until now.  As far as writing the tests so that the JIT code will be run, you can either write the test recursively, e.g.

fooTest
    self fooTest: 0

fooTest: n
    n < 2 ifTrue: [^self fooTest: n + 1]. "Make sure method is JITTED"
   ...

or run the tests in a block and make sure the block is repeated, say, 10 times.  There is a secret primitive in the VM one can use to test for JITTED ness.  See Context>>X-ray in Cog-Tests.  If you need this in the KernelTests then you can add it as an extension.

xray
	"Lift the veil from a context and answer an integer describing its interior state.
	 Used for e.g. VM tests so they can verify they're testing what they think they're testing.
	 0 implies a vanilla heap context.
	 Bit 0 = is or was married to a frame
	 Bit 1 = is still married to a frame
	 Bit 2 = frame is executing machine code
	 Bit 3 = has machine code pc (as opposed to nil or a bytecode pc)
	 Bit 4 = method is currently compiled to machine code"
	<primitive: 213>
	^0 "Can only fail if unimplemented; therefore simply answer 0"

**Comment by eliotmiranda** [comment]
also, in e.g. CogObjectRepresentationFor64BitSpur>>genFloatComparison:orIntegerComparison:invert:boxed: or anywhere else the issue comes up it would be good for non-experts to extend the comment, so that instead of just

	"If floatRcvr == (double) intArg then use compareInt(intArg,(int64) floatRcvr)"

it says
	"If floatRcvr == (double) intArg then use compareInt(intArg,(int64) floatRcvr).
	 see https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/417"
or
	"If floatRcvr == (double) intArg then use compareInt(intArg,(int64) floatRcvr).
	 because in 64-bits SmallInteger has more significant bits (60) than Float (53)"

**Comment by eliotmiranda** [comment]
One last nit; there is no need to use
	self cppIf: objectMemory wordSize > 4 ifTrue: [ ... ] ].
One can simply write
	objectMemory wordSize > 4 ifTrue: [ ... ].

This is because VMMaker generates entirely different sources for 64-bit and 32-bit VMs, and so the objectMemory wordSize > 4 test is inlined at source generation time.  Reserve cppIf:ifTrue: for things that really are VM-compile-time options, such as whether the VM is being compiled with IMMUTABILITY (read-only) support or not.
