### ISSUE TITLE
Latest Linux VM can't handle -vm-display-null

### ISSUE THREAD

**Issue by theseion** [OpenSmalltalk/opensmalltalk-vm#421]
On Linux (Debian 10, Ubuntu 14.04.5) `curl get.pharo.org/64/vmLatest80 | bash; ./pharo` fails with
> could not find module vm-display-null

**Comment by bencoman** [comment]
Just to flesh this out, try `./pharo -nodisplay`

**Comment by theseion** [comment]
I did. I just thought I'd provide the shortest possible instruction ;)

**Comment by theseion** [comment]
I figured out which build broke the functionality but I don't know which commit it might have been. The last good build is https://bintray.com/opensmalltalk/vm/cog/201907242041, the first bad build is https://bintray.com/opensmalltalk/vm/cog/201907310030. There's one build that is also bad but somehow out of sequence, that's https://bintray.com/opensmalltalk/vm/cog/201907141817.

**Comment by theseion** [comment]
It seems that some OpenGL headers are missing. Even though the builds appear to be green, the pharo.cog.spur builds terminate early because the B3DAcceleratorPlugin can't be built due to those missing headers. I'm still investigating the details but at least `libglu1-mesa-dev` has to be installed. It's possible that the build cache / third-party cache has been hiding this problem for quite some time and a recent change to the source of the plugin has caused recompilation.
The effect of the termination is that not all libraries have been installed before packaging.

CC @nicolas-cellier-aka-nice since you appear in the list of recent commits to the plugin.
