### ISSUE TITLE
Where to find VM .st source code?

### ISSUE THREAD

**Issue by ljulliar** [OpenSmalltalk/opensmalltalk-vm#423]
Hi everyone,

Sorry for this newbie question but I'm unclear as to where I can the Smalltalk/Slang source code for the VM and the associated Slang to C translator.

Thank you for your help!

**Comment by nicolas-cellier-aka-nice** [comment]
It's better to answer here directly.
Most Slang source is managed in this Monticello repository https://source.squeak.org/VMMaker
You can submit your changes to https://source.squeak.org/VMMakerInbox

But there are still some plugins hanging here and there.
Eliot provide the recipe to build a ready-to-use Squeak image, and I guess it's a tiny bit more involved from Pharo which shall require some compatibility layer.
See https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/image/BuildSqueakSpurTrunkVMMakerImage.st

**Comment by clementbera** [comment]
The question was answered, and not update since Sept 3. I close this issue.
