### ISSUE TITLE
primitiveFileSize fails on Stdio handles

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#430]
`FileStream stdout closed` returns `true` in a currently Squeak trunk image. The reason for this is that the `primitiveFileSize` fails. To be fair, it makes sense as `stdout` does not really have a size. Nonetheless, it does not make sense that Squeak thinks `stdout` is closed, especially when it really isn't. On SqueakJS, for example, the primitive returns `0` which lets `FileStream stdout closed` return `false`.

I'm not sure where to fix this, probably in the `FilePlugin` code of VMMaker? Could someone please take a look? Thanks!

See also: http://forum.world.st/FileStream-stdout-closed-td5105395.html

**Comment by eliotmiranda** [comment]
Got to this today.
