### ISSUE TITLE
primitiveUtcWithOffset broken

### ISSUE THREAD

**Issue by marceltaeumel** [OpenSmalltalk/opensmalltalk-vm#488]
```
VM 202004210425 (cog.spur 32-bit and 64-bit)
OS Windows 10 (Version 1909 Build 18363.778)
```

Today is -- obviously -- January 19 in the wonderful year of 586155. 😄 

The primitive used in `Time class >> #primPosixMicrosecondClockWithOffset:` called `primitiveUtcWithOffset` returns strange information.

Works fine in `VM 202003021730`.

**Comment by nicolas-cellier-aka-nice** [comment]
The first value returned by `primPosixMicrosecondClockWithOffset` looks like `0 - epochDelta \\ (1<<64)` where `epochDelta` is the microseconds between Squeak epoch (1901) and unix epoch (1970).

IOW, it's like if `ioUTCMicroseconds()` is returning 0 or near 0...

**Comment by nicolas-cellier-aka-nice** [comment]
Hmm, I might be guilty:

https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/9d52fef2240b7bdf6cfa1a7d6cf8c967220f0e85

gonna check C precedence of operators...

**Comment by nicolas-cellier-aka-nice** [comment]
bah, it's obviously 0, if only I used bitOr instead of bitAnd, it could have worked... Sorry
