### ISSUE TITLE
trackpad scroll events handled improperly on macOS Sierra with squeak.cog.spur

### ISSUE THREAD

**Issue by ccrraaiigg** [OpenSmalltalk/opensmalltalk-vm#49]
Strange selection behavior when nothing should happen... To duplicate, scroll to the top or bottom of a text pane using a two-finger scroll trackpad gesture, and keep scrolling after you get there. This doesn't happen with a non-trackpad mouse, or with older versions of the Squeak VM on the same OS.

If someone can get to this before I have time, please feel free. Thanks!

**Comment by nicolas-cellier-aka-nice** [comment]
I think that these are those horizontal scroll events that were added by Pharo VM.
I'd like them filtered out, because I never want to select text like that, nor make any of my lists flashing like mad.

**Comment by nicolas-cellier-aka-nice** [comment]
This should be resolved in latest VM (including the one distributed with Squeak 5.3).
Report problems if persisting after the upgrade.
I close this issue
