### ISSUE TITLE
Proposal for new BitBlt rules

### ISSUE THREAD

**Issue by jvuletich** [OpenSmalltalk/opensmalltalk-vm#505]
In addition to the existing alpha blending rules (24 and 34), I propose 3 new additional rules.

Check https://en.wikipedia.org/wiki/Alpha_compositing 

Existing rule 34 is a correct implementation of Alpha Blending for scaled forms, i.e. if premultiplied alpha is used. But rule 24 is a correct implementation of non-scaled forms, only for the case where destination is opaque (i.e. it's alpha is 1.0 in every pixel). If destination includes translucency (or it is completely transparent), the result is not correct. In order to fix it, the RGB of each pixel need to be divided by the pixel alpha.

The proposed blendUnscaled is the basic (for non-scaled forms) alpha blending described in Wikipedia. Note that users knowing that destination background is opaque might call the faster rule 24 instead.

The other two additional proposed rules are for converting to and from premultiplied alpha.

EXISTING blend 24	alphaBlend
resultAlpha = srcAlpha + destAlpha*(1-srcAlpha)
resultRGB   = srcAlpha*source + (1-srcAlpha)*dest

EXISTING blendAlphaScaled	34	alphaBlendScaled
resultRGBA = source + (1-srcAlpha)*dest

NEW PROPOSED multiplyRGBByAlpha
Non premultiplied alpha -> premultiplied alpha. Only uses destination. Alpha unmodified. For each RGB component,
resultRGB = dest*destAlpha

NEW PROPOSED divideRGBByAlpha
Premultiplied alpha -> non premultiplied alpha. Only uses destination. Alpha unmodified. For each RGB component,
resultRGB = dest/destAlpha

NEW PROPOSED blendUnscaled
Equivalent to blend, and then divideRGBByAlpha
resultAlpha = srcAlpha + destAlpha*(1-srcAlpha)
resultRGB   = (srcAlpha*source + (1-srcAlpha)*dest) / resultAlpha

This would allow handling of scaled (premultiplied-alpha) forms, and blending of regular forms including translucency, without the need to call slower smalltalk code to fix the results.

**Comment by jvuletich** [comment]
Yep. That's right.

**Comment by hilaire** [comment]
Thanks Juan to report it.

**Comment by marceltaeumel** [comment]
Would be nice to also have the Smalltalk fall-back code for those new rules. :-)

**Comment by nicolas-cellier-aka-nice** [comment]
WIP http://source.squeak.org/VMMaker/VMMaker.oscog-nice.2909.diff

**Comment by nicolas-cellier-aka-nice** [comment]
I won't provide any accelerated assembler for the new ops, not my cup of tea.
But as I understand it, the PI will fall back to the code generated for the BitBlt plugin when no accelerated path is provided, so it should continue to work.
What would be nice now would be to start writing image side code & unit tests in either Cuis or Squeak.

**Comment by nicolas-cellier-aka-nice** [comment]
http://source.squeak.org/inbox/GraphicsTests-nice.57.diff
http://source.squeak.org/inbox/Graphics-nice.442.diff

**Comment by nicolas-cellier-aka-nice** [comment]
I have revised the implementation which was previously not correct.
See https://source.squeak.org/VMMaker/VMMaker.oscog-nice.3170.diff
and also the image-side tests
See https://source.squeak.org/inbox/GraphicsTests-nice.58.diff
the image side tests pass on locally generated VM

**Comment by nicolas-cellier-aka-nice** [comment]
integrated in https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/f77943115bbb8e55fc1adeaf54f483ecc6024bc6
