### ISSUE TITLE
Cannot build unix sources (missing file: bld/plugins.int)

### ISSUE THREAD

**Issue by LinqLover** [OpenSmalltalk/opensmalltalk-vm#507]
I am trying to build the unix sources for this project, exactly following the `HowToBuildFromSources` manual (the easy way). But unfortunately, when running `make` I get an error that `bld/plugins.int` is missing:

```console
$ cd platforms/unix/
$ make
[ -d bld ] || mkdir bld
[ -f bld/Makefile ] || ( cd bld; ../config/configure; )
checking for gcc... gcc
# ... (75 lines skipped)
checking whether to build static libraries... no
/workspace/opensmalltalk-vm/src
/workspace/opensmalltalk-vm/src/plugins
checking sanity of generated src directory... bad
missing file: /workspace/opensmalltalk-vm/platforms/unix/bld/plugins.int
make: *** [Makefile:5: all] Error 1
```

See yourself:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#snapshot/9bc102f3-ba84-437f-a226-a8851782c41b)

Is it me or is the documentation of the build process not up to date? Looking forward to your help!

**Comment by kksubbu** [comment]
The instructions in HowToBuildFromSources are for the old squeakvm. For Cog, use the mvm script under the various build directories based on platform/wordsize/ISA and then product/interpreter/object-memory. Here you will find the plugins.int and plugins.ext files.  Now choose the build directory for your build variant (production, assert, debug etc.).

Example,

   $ cd build.linux64x64/squeak.cog.spur/build
   $ ./mvm

**Comment by LinqLover** [comment]
Thank you very much for your help, Subbu. So now I ran exactly your two commands, but first, the build failed because it was missing `clang`. Do I assume correctly that the following dependency should be mentioned anywhere in the repository?

```sh
sudo apt-get -y install clang
```

However, after installing clang and trying again, the build still fails.

The output contains the following errors:

- ```
  error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
  ```
- ```
  /mnt/c/Users/Christoph/OneDrive/Dokumente/Squeak/Christoph/git/opensmalltalk-vm/platforms/Cross/plugins/B3DAcceleratorPlugin/B3DAcceleratorPlugin.h:14:13: fatal error: 
  /mnt/c/Users/Christoph/OneDrive/Dokumente/Squeak/Christoph/git/opensmalltalk-vm/platforms/Cross/plugins/B3DAcceleratorPlugin/B3DAcceleratorPlugin.h:14:13: fatal error: 'GL/gl.h' file not found
  #   include <GL/gl.h>
              ^~~~~~~~~
  1 error generated.
  Makefile:179: recipe for target 'B3DAcceleratorPlugin.lo' failed
  make[1]: *** [B3DAcceleratorPlugin.lo] Error 1
  Makefile:543: recipe for target 'B3DAcceleratorPlugin.la' failed
  make: *** [B3DAcceleratorPlugin.la] Error 2
  ```
- Additionally, I am getting a large number of 177 warnings, which are probably not so important?

Could you tell me where I can get the `gl.h` header?

**Comment by kksubbu** [comment]
On 12/06/20 8:35 pm, Christoph Thiede wrote:
> Thank you very much for your help, Subbu. So now I ran exactly your two 
> commands, but first, the build failed because it was missing |clang|. Do 
> I assume correctly that the following dependency should be mentioned 
> anywhere in the repository?
> 
> sudo apt-get -y install clang

I haven't used clang. I use the gcc toolchain. Sorry

> 
>   *
> 
>     |error: unknown warning option '-Wno-unused-but-set-variable'; did
>     you mean '-Wno-unused-const-variable'?
>     [-Werror,-Wunknown-warning-option] |

gcc has the unused-but-set-variable warning that gets suppressed with 
that flag. See https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

If you use clang, you will have to find the equivalent.

>     fatal error: 'GL/gl.h' file not found # include <GL/gl.h> ^~~~~~~~~

This is found in mesa-common-dev package which gets install 
automatically as a dependency for libgl1-mesa-dev.

> 
>   * Additionally, I am getting a large number of 177 warnings, which are
>     probably not so important?

If I were you, I would scan through the warnings on 64b compile just to 
make sure I am not missing anything important. Both int and pointer were 
32b on 32b compile so one could force a pointer into int. But a pointer 
is 64b on 64bit compiles. Storing a pointer into a int is problematic.

Regards .. Subbu

**Comment by LinqLover** [comment]
Hi Subbu, thank you again! After installing `libgl1-mesa-dev`, the build process ran successfully, however it was still missing that clang flag.

My questions are resolved so far, but I believe that further people could benefit from the exact documentation of the necessary dependencies:

> > first, the build failed because it was missing `clang`. Do I assume correctly that the following dependency should be mentioned anywhere in the repository?
> >
> > ```
> > sudo apt-get -y install clang
> > ```
>
> I haven't used clang. I use the gcc toolchain. Sorry

Which exact packages do I have to install? The `platforms/unix/config/configure` script requires `clang` to be installed as noted above. At the moment I have installed `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0` and `clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)`, but that clang version does not understand the `no-unused-but-set-variable` flag. Could you maybe refer to a specific package? :-)

I just read the `HowToBuild` file in the `build.linux*` directory. I installed the package string listed for Ubuntu, but the clang flag is still not recognized ...

**Comment by LinqLover** [comment]
> Does the configure script not check for the presence of the OpenGL headers?

Am I just talking to an intelligent bot? :-) No, at least I did not found an error referring to this particular problem.

**Comment by j4yk** [comment]
That was me, replying to the mailing list. ;-)

**Comment by LinqLover** [comment]
Ah, the bot should mention this :-)

**Comment by eliotmiranda** [comment]
Can we close this issue now?

**Comment by LinqLover** [comment]
@eliotmiranda My concrete problem was resolved, but it might be helpful for others to add some exact documentation of the dependencies needed for the build without using cygwin. Feel free to close if you think this is not important. :-)

**Comment by LinqLover** [comment]
I am having the very same problem as described at the beginning of this thread on a new Ubuntu 24.04 machine, can you please reopen this issue?

```
cd platforms/unix
make
# install all mentioned dependencies from building/inux64x64/HowToBuild
sudo apt install clang
```

```
...
checking sanity of generated src directory... bad
missing file: /home/Christoph.Thiede/gitc/OpenSmalltalk/opensmalltalk-vm/platforms/unix/bld/plugins.int
make: *** [Makefile:5: all] Error 1
```

I am using clang version 18.1.3 (1ubuntu1). What am I doing wrong? Where is the `plugins.int` file? Thanks in advance.
