### ISSUE TITLE
win64x64.squeak.cog.spur silently crashes on save or save&quit

### ISSUE THREAD

**Issue by marceltaeumel** [OpenSmalltalk/opensmalltalk-vm#535]
No crash dump. It just closes. Not sure why exactly. Last time, it happened after loading Metacello and Squot in Squeak 5.3. Before it happened in Trunk after playing around with FFI and OpenGL. So, it is not related to FFI. The VM silently closes on "save" or "save and quot". 

VM: 202011120327 (win64x64.squeak.cog.spur)
OS: Windows 10 (2004 Build 19041.630)
Squeak: latest 5.3 or 6.0alpha

**The .image file is not corrupted after this crash!** It just did not write anything to it.

Here is the report that Windows generated:

```
Quelle
Squeak Cog Spur Virtual Machine

Zusammenfassung
Nicht mehr funktionsfähig

Datum
‎14.‎11.‎2020 11:25

Status
Der Bericht wurde gesendet.

Beschreibung
Pfad der fehlerhaften Anwendung:	C:\Tools\squeak_53_ecoop\Squeak.exe

Problemsignatur
Problemereignisame:	APPCRASH
Anwendungsname:	Squeak.exe
Anwendungsversion:	2020.11.12.327
Anwendungszeitstempel:	00000000
Fehlermodulname:	Squeak.exe
Fehlermodulversion:	2020.11.12.327
Fehlermodulzeitstempel:	00000000
Ausnahmecode:	c0000005
Ausnahmeoffset:	0000000000033cd5
Betriebsystemversion:	10.0.19041.2.0.0.768.101
Gebietsschema-ID:	1031
Zusatzinformation 1:	e064
Zusatzinformation 2:	e0644d1b3ac5fae3d6c60b42d946256e
Zusatzinformation 3:	4588
Zusatzinformation 4:	45886eecb7a8f73a86ab34ad6194fd79

Weitere Informationen über das Problem
Bucket-ID:	5801b02358401c93cbecf9af1e413cb3 (2012257664049953971)
```

**Comment by eliotmiranda** [comment]
Yes, I’m seeing this too on MacOS.  I’ve caused a regression.  I suspect it was the changes I made to pinning/unpinning the display bitmap on snapshot. I’ll revert and see if it fixes it.  But there are other changes.  If anyone has the patience to bisect and find out exactly which commit is responsible that would be great.

**Comment by eliotmiranda** [comment]
I can confirm that 4c31c557b15b7f4052ad46dae300bbb308c875e7 is good.

**Comment by marceltaeumel** [comment]
> I can confirm that [4c31c55](https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/4c31c557b15b7f4052ad46dae300bbb308c875e7) is good.

Hmm... that commit was 4 days ago? Well, I also experienced that bug today on a 202011091413 VM (32-bit), that is, from 6 days ago.

**Comment by eliotmiranda** [comment]
Hi Marcel, it should be fixed in 400dfa3fddce98a0b9127b3981109b5ec61623a5
Apologies for the loss of snapshots!!

**Comment by marceltaeumel** [comment]
Thanks! I am building it now to try it during the next days. I will report back.

**Comment by eliotmiranda** [comment]
Fixed right?
