### ISSUE TITLE
Bintray has reached end-of-life, where can we download the bleeding-edge releases now?

### ISSUE THREAD

**Issue by LinqLover** [OpenSmalltalk/opensmalltalk-vm#564]
Is it possible to migrate to GitHub prereleases? Also, the badge in the README should be updated.

**Comment by marceltaeumel** [comment]
readme.md is up to date. See:
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/latest-build
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/latest-assert-build
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/latest-debug-build
