### ISSUE TITLE
build.win64x64 fails: No rule to make target 'build/vm/ADPCMCodecPlugin.lib'

### ISSUE THREAD

**Issue by j4yk** [OpenSmalltalk/opensmalltalk-vm#568]
I want to learn about plugin development and intended to start with a VM build first. Using Cygwin 64 bits with mingw64-x86_64-clang, I build from the build.win64x64/squeak.cog.spur directory.

The build fails at this point; notably it is not a compiler error, but a make error:

```
...
rm -f build/vm/ADPCMCodecPlugin.ignore
make  BUILD=build \
        -f /cygdrive/c/Squeak/Wincred-Plugin/opensmalltalk-vm/build.win64x64/common/Makefile.plugin \
        build/vm/ADPCMCodecPlugin.lib
make[1]: Entering directory '/cygdrive/c/Squeak/Wincred-Plugin/opensmalltalk-vm/build.win64x64/squeak.cog.spur'
make[1]: *** No rule to make target 'build/vm/ADPCMCodecPlugin.lib'.  Stop.
make[1]: Leaving directory '/cygdrive/c/Squeak/Wincred-Plugin/opensmalltalk-vm/build.win64x64/squeak.cog.spur'
make: *** [../common/Makefile:280: build/vm/ADPCMCodecPlugin.lib] Error 2
```

I think I followed all the instructions of the main README.md and build.win64x64/HowToBuild. What can I do to deal with this issue and get the build going?

**Comment by j4yk** [comment]
Invoked the build with `./mvm -f`.

**Comment by j4yk** [comment]
I have tried to comment out plugins from the plugins.int file. It seems that all of them run into the same issue. I have given up that attempt after I reached DropPlugin and it still reported "No rule to make target 'build/vm/DropPlugin.lib'."

**Comment by dtlewis290** [comment]
Not sure if this helps (I don't have Windows to check) but there are unresolved issues in the Linux builds that may affect you here also, see https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/562. Suggestion - try checking out the fix_include_order branch and see if it works, or check out any older version prior to aafcb78371c7e576073a8dbf2f1f32667568e05e.

**Comment by j4yk** [comment]
Thank you David, on the fix_include_order branch, the build works, although I could not quite believe it at first.

Now I suppose that the Makefile system does not stop early enough on errors, because it did not reveal the actual errors that happened before the libraries were found missing. I guess I will find them in the log if I switch the branch again and scroll up, but in my opinion, this should not be necessary.

Anyway, I can continue my learning path now. :-)

**Comment by marceltaeumel** [comment]
Fixed and merged. #572
