### ISSUE TITLE
Aarch64 integer compare bug (#<)

### ISSUE THREAD

**Issue by KenDickey** [OpenSmalltalk/opensmalltalk-vm#571]
16r80000000 < 16r8000000000000000.  "==> false "

[Intel reports true]

**Comment by codefrau** [comment]
That is indeed a great test case that might help narrow it down:

If you "debug into it" you should see that primitive 3 failed for SmallInteger, and it falls back to Integer's version of `<`. If it doesn't, then it's either the JIT incorrectly short-circuiting the comparison, or primitive 3 incorrectly succeeding.

If instead you do see the super send (as is the case on Intel), then it must be primitive _primDigitCompare_ in LargeIntegers plugin. 

Very much sounds like a signed/unsigned problem.

**Comment by KenDickey** [comment]
On 2021-06-17 11:57, Vanessa Freudenberg wrote:

> That is indeed a great test case that might help narrow it down:
> 
> If you "debug into it" you should see that primitive 3 failed for 
> SmallInteger, and it falls back to Integer's version of <. If it 
> doesn't, then it's either the JIT incorrectly short-circuiting the 
> comparison, or primitive 3 incorrectly succeeding.

Tried "Debug It" + "Setp Into" in Squeak and Cuis.  Both return 'false' 
without interior detail.

Also same with current 
~/OpenSmalltalk/oscogvm/build.linux64ARMv8/squeak.cog.spur/build
as well as the "ARMv8 BitBLT speedups provided by RPi/Ben Avison" VM.

vvv==========================vvv
Chromebook:Linux:Arm64:~/Squeak5.3 >>> squeak --version
5.0-202103220146  Sat May 22 19:42:47 PDT 2021 gcc 8 [Production Spur 
64-bit VM]
CoInterpreter VMMaker.oscog-eem.2948 uuid: 
935d1ee7-0e61-47a5-92e2-953224c7ffcf May 22 2021
StackToRegisterMappingCogit VMMaker.oscog-eem.2946 uuid: 
461911e1-d450-4f05-8a40-7b0470487041 May 22 2021
VM: 202103220146 ***@***.***:OpenSmalltalk/Bavison
Date: Sun Mar 21 21:46:24 2021 CommitHash: d494240
Plugins: 202103220146 ***@***.***:OpenSmalltalk/Bavison
Linux penguin 5.4.99-12983-g8b7876ab9f5e #1 SMP PREEMPT Sun Feb 21 
11:49:16 PST 2021 aarch64 GNU/Linux
plugin path: /usr/local/bin/../lib/squeak/5.0-202103220146 [default: 
/usr/local/lib/squeak/5.0-202103220146/]
Chromebook:Linux:Arm64:~/Squeak5.3 >>>
...
Chromebook:Linux:Arm64:~/OpenSmalltalk/oscogvm/products/sqcogspur64ARMv8linuxht/lib/squeak/5.0-202106162331 
 >>> ./squeak --version
5.0-202106162331  Wed Jun 16 16:39:14 PDT 2021 gcc 8 [Production Spur 
64-bit VM]
CoInterpreter VMMaker.oscog-eem.2967 uuid: 
57b9e5f9-0212-436d-acaf-4e501e470621 Jun 16 2021
StackToRegisterMappingCogit VMMaker.oscog-eem.2953 uuid: 
9f3d924e-9226-4242-9b6f-3dad93c7a837 Jun 16 2021
VM: 202106162331 ***@***.***:OpenSmalltalk/oscogvm
Date: Wed Jun 16 16:31:37 2021 CommitHash: 58e8b33db
Plugins: 202106162331 ***@***.***:OpenSmalltalk/oscogvm
Linux penguin 5.4.109-26077-g12746d86825a #1 SMP PREEMPT Mon May 17 
21:46:50 PDT 2021 aarch64 GNU/Linux
plugin path: 
/home/kendi3he/OpenSmalltalk/oscogvm/products/sqcogspur64ARMv8linuxht/lib/squeak/5.0-202106162331/ 
[default: 
/home/kendi3he/OpenSmalltalk/oscogvm/products/sqcogspur64ARMv8linuxht/lib/squeak/5.0-202106162331/]

^^^==========================^^^

**Comment by codefrau** [comment]
Thanks for testing that. My guess then would be that the jitted code for `<` fails to recognize 16r8000000000000000 as being a LargeInteger (which is unlikely), or knowing it's a LargeInt but thinking it can handle the comparison quickly and failing to do so correctly.

**Comment by ccrraaiigg** [comment]
Has anyone built the GdbARMv8Plugin on a Raspberry Pi? It seems to have major issues with the include files when I do it.

**Comment by krono** [comment]
a0d15af closes this

**Comment by eliotmiranda** [comment]
> On Jul 1, 2021, at 10:54 PM, Tobias Pape ***@***.***> wrote:
> 
> ﻿
> a0d15af closes this
> 

But it doesn’t close the issue of not being able to build the GdbARMv8Plugin.  Tim, where and how does the build fail?

Have you built the plug-in on eg Mac to see how the build directory is organized?  Is the support in build.linux64ARMv8/gdbarmv8 (IIRC?) etc?

**Comment by ccrraaiigg** [comment]
I built GdbARMv8Plugin on macOS 11.4 (Intel) without a hitch, but during use it failed primitively before doing any actual work, during its startup.

Before that I tried to build in Ubuntu 21 Linux on a Raspberry Pi 4, but there were multi-level header-ordering problems even worse than the one involving Linux features.h and our sq.h. When I got to the point of two Linux headers both saying they should be included before the other, I stopped. The support in build.linux64ARMv8/gdbarm64 did seem to be as expected, including conf.COG and makeeem.

**Comment by KenDickey** [comment]
Verified fixed in interpreter VM on Arn64 Chromebook and RasPi4.

Thanks a bunch!!

**Comment by eliotmiranda** [comment]
> On Jul 2, 2021, at 10:28 AM, Craig Latta ***@***.***> wrote:
> 
> 
> I built GdbARMv8Plugin on macOS without a hitch, but during use it failed primitively before doing any actual work, during its startup.
> 
> 
I found on macOS 11.x I needed to change the entitlements to include 
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>

and I just committed this by mistake.  Turns out it does no harm on a 10.14.x build.  I no longer have a 10.13.x build environment.  So I don’t know if this will break older builds.

It also appears that moving to 10.14.x or later kills 32-bit builds.  I used to be able to build 32-bit VMs on 10.13.x.

**Comment by krono** [comment]
Hi

> 
> It also appears that moving to 10.14.x or later kills 32-bit builds. 

seems so.

Apple is issuing warning on first start of every 32-bit application that they'd be unsupported on 10.14.


> I used to be able to build 32-bit VMs on 10.13.x.

mvm breaks with
```
MathPlugin.c deps/FloatMathPlugin.d
make[1]: *** No rule to make target `../../platforms/Cross/plugins/FloatMathPlugin/fdlibm/e_acos.c', needed by `build/FloatMathPlugin/acos.o'.  Stop.
make: *** [build/vm/FloatMathPlugin.lib] Error 2
```

but this looks actually unrelated…

My uneducated guess is that the entitlement makes no difference…
