### ISSUE TITLE
JIT failing testMediumIntegerDiv and testMediumIntegerRem

### ISSUE THREAD

**Issue by rmacnak** [OpenSmalltalk/opensmalltalk-vm#6]
From Newspeak's KernelTestsConfiguration, these tests pass on the stack VM but fail on the JIT.

```assert: minInt31 // -1 equals: 1073741824.```
Equality assertion failed; expected: 1073741824, was: -1073741824

```assert: (minInt31 rem: -1) equals: 0.```
Equality assertion failed; expected: 0, was: -2147483648

**Comment by timfel** [comment]
I think we should include running some tests in a CI job also. Right now we're just testing if it compiles ("regression testing"? What's that? If it compiles, it is good -http://lkml.iu.edu/hypermail/linux/kernel/9804.1/0149.html)

**Comment by eliotmiranda** [comment]
Ryan,  I think this is fixed.  I could close or could leave it up to you to verify.

**Comment by rmacnak** [comment]
I can verify this is fixed in Monticello, but not in Git. Leaving the issue open until the fix lands here.

**Comment by rmacnak** [comment]
Fixed by a8e42ed08b27fabd9a110fc069d9f0263005fe9b.
