### ISSUE TITLE
Cannot resolve domain names longer than 64 characters on linux

### ISSUE THREAD

**Issue by smalltalking** [OpenSmalltalk/opensmalltalk-vm#619]
SocketPlugin uses a buffer of size MAXHOSTNAMELEN + 1 on [unix](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/6d38f13347be1031168b8b02e8ca52dc1b74be1c/platforms/unix/plugins/SocketPlugin/sqUnixSocket.c#L212).
The value of that constant is 64 on linux. A domain name can have up to 255 octets with each label having up to 63 octets.
So, 64 is definitely not the right value, nor is MAXHOSTNAMELEN, because the buffer is there to store a domain name, not a host name.

**Comment by krono** [comment]
I had a similar problem in SqueakSSL so I just defined it as such: https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/platforms/unix/plugins/SqueakSSL/sqUnixOpenSSL.inc#L44
