### ISSUE TITLE
Boot parameter -headless ignored in Windows 10

### ISSUE THREAD

**Issue by nmingotti** [OpenSmalltalk/opensmalltalk-vm#639]
Hi, 
I am trying to deploy CuisSmalltalk as a scripting language in Windows 10. 
I am running the latest release of the VM
 `Win32 built on Jun  2 2022 15:29:46 Compiler: Clang 14.0.3 [Production Spur 64-bit X64 VM]`.
I got almost all working but I found this little roadblock.
As far as I can say the "-headless" parameter is ignored in Windows 10. 
---- demo, headless is ignored. 
```
win cmd> C:\CUIS\squeak.cog.spur_win64x64\SqueakConsole.exe -headless C:\CUIS\Cuis6.0-5031.image 
                                -d "StdIOWriteStream stdout nextPutAll: 'hello world'; newline." 
                                -d "Smalltalk quit."

=> hello world   [ headless is not working, if you remove the 'Smalltalk quit' you will see the window is well alive].
```

By comparison the parameter "-vm-display-null" works very well in Linux. 
---- demo, fully working
```
$> ./sqcogspur64linuxht/squeak -vm-display-null Cuis-Smalltalk-Dev/Cuis6.0-5031.image 
           -d "StdIOWriteStream stdout nextPutAll: 'Hello World'; newLine" 
           -d 'Smalltalk quit.' 

=> Hello World     [and goodbye]
```

bye
Nicola

**Comment by marceltaeumel** [comment]
Hmm... originally, that "headless" mode under Windows only tried to hide the window in the tray bar. Recent Windows versions seem to be persistent in re-raising that window once it gets hidden. How annoying. In any case, there has never been an actual "headless mode" for Windows.

**Comment by nmingotti** [comment]
Aaaah, pity ! If anybody knows Windows well enough to implement it this would be a very useful feature to have in the VM. I think Cuis, Squeak and Pharo (i speak for the 3 i tried) can do well in scripting. And they are easier to manage than Python for this reason: 1 dirctory with the VM, 1 image, 1 bat file and voilà your script is transported and independent from the rest of the system configuration. This is an exceptionally good thing for a system manager. Porability+Independence. Worth considering... ok, so, for the moment I can try with some ugly hack, like saving the image in a minimized state, or something like that. bye

**Comment by nmingotti** [comment]
I have seen the "service" option is some other posts around. But, as the name implies, services stay up for a long time. What I was running in this case is a single shot script. It runs quite fast, a few times per day. But should not be visible to the user, that is undesirable. bye

**Comment by nmingotti** [comment]
Hi Tim, umm, nope, it would be a big twist. What happens is this, there an analysis machine which has Windows IoT OS. When the builtin software finishes an analysis phase there is the option to run an executable of your choice. Here I run my stuff. Consider the analysis phase is long, takes at least 20 seconds, so nobody will notice if my script runs in 0.5 sec.

**Comment by nmingotti** [comment]
Just checked, the VM works in Windows 10 IoT, no problem on that. For the moment i leave the problem open,  i don't know how to fix this. I guess a light change to SqueakConsole.exe might do the trick, but i can't pick that up now, too far into the realm of things i never did ;) If i find an hack to close the issue i will report. bye

**Comment by nmingotti** [comment]
I found the hack to circumvent the problem. Uses Powershell. This is the starting point.
```
ps>  Start-Process .\squeak.cog.spur_win64x64\Squeak.exe -ArgumentList .\borghiSerialExpoter.image -WindowStyle Minimized
```

I close the issue, still if anybody is able to fix `-headless`, well that would be better;) bye.
