### ISSUE TITLE
Win32 commandline Squeak start-up script ignored

### ISSUE THREAD

**Issue by alandao** [OpenSmalltalk/opensmalltalk-vm#655]
I'm trying to run a Smalltalk script on VM start-up on Windows. It looks like GNU/Linux is able to do it with this command:
`../cogspur/squeak Cuis5.0-4426 -s ../scripts/setUpEnvironment.st`

However, the start-up script is ignored when I try this equivalent command on Windows:
`cogspur\Squeak.exe Cuis5.0-4426.image -s ../scripts/setUpEnvironment.st`

Is there a Windows equivalent way to run a script on VM start-up?

**Comment by alandao** [comment]
I’ve also tried without the -s flag and it didn’t work either :(

**Comment by krono** [comment]
So you used `cogspur\Squeak.exe Cuis5.0-4426.image -s ../scripts/setUpEnvironment.st` on Windows.
I don't know where path normalization kicks in, but what about
`cogspur\Squeak.exe Cuis5.0-4426.image -s ..\scripts\setUpEnvironment.st`? 

Also, in the past, the script sometimes needed to be an absolute path, maybe try that too?

**Comment by eliotmiranda** [comment]
You must use SqueakConsole.exe; Windows is badly broken like that.  Command line arguments are not passed along for Squeak.exe.

When the system is running you can check that the arguments are available via getSystemAttribute: and senders (eg Squeak has SmalltalkImage>>rawArguments and SmalltalkImage>>arguments; not sure what Cuis provides).

**Comment by alandao** [comment]
> You must use SqueakConsole.exe; Windows is badly broken like that. Command line arguments are not passed along for Squeak.exe.
> 
> When the system is running you can check that the arguments are available via getSystemAttribute: and senders (eg Squeak has SmalltalkImage>>rawArguments and SmalltalkImage>>arguments; not sure what Cuis provides).

So, I checked the available system attributes w/ `getSystemAttribute:` in Cuis and saw that all my Windows command line args are passed into the image as system attributes properly on SqueakConsole.exe _and_ Squeak.exe. After I did a few changes to my Cuis image, I was able to get my start-up script running! I'm confident the issue here is actually related to the Cuis image and has nothing to do with OpenSmalltalk. I'll go ahead and close this issue and let the Cuis maintainers know.

Thanks for the help!

**Comment by alandao** [comment]
I’ve also tried without the -s and it didn’t work either :(
