### ISSUE TITLE
Running 6502 image on 64bit Linux

### ISSUE THREAD

**Issue by Kirtai** [OpenSmalltalk/opensmalltalk-vm#656]
I'm trying to revive a 6502 image (MicroSqueak) but can't seem to find a release or a way to build a VM to run this on my 64bit EndeavourOS (Arch derivative) system. Am I missing something or is that not supported any more?

**Comment by krono** [comment]
Hi.
The lowest version OpenSmalltalk-VM can handle seems to be `6505` (see [ckformat](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/src/ckformat.c) for a list).

The traditional SqueakVM Repo at http://squeakvm.org/unix/ might contain the sources you need.
Please report here if you have trouble!

**Comment by krono** [comment]
(PS: 6502 is a 32-bit Image format. It will be _a lot_ of work to make this run on 64-bit Linux. It is possible although really complicated)

**Comment by Kirtai** [comment]
I got it running in SqueakJS.

I'll have a look at the old VMs later should I need them.

**Comment by Kirtai** [comment]
Thanks everyone :)
