### ISSUE TITLE
The VM is no longer passing command line arguments to the image

### ISSUE THREAD

**Issue by stormwatch** [OpenSmalltalk/opensmalltalk-vm#668]
# How to replicate:
Run `<path to release candidate.app> <image> one two three four`.

Then evaluate:
```Smalltalk
| i a |
i := 0.
a := Smalltalk getSystemAttribute: i.
[a notNil] whileTrue: [
	Transcript showln: { i. a}.
	i := i + 1.
	a := Smalltalk getSystemAttribute: i ].
```

# Expected behaviour as in the latest stable relase (2022)
The transcript logs all command line arguments:
> #(0 '/Users/eze/.local/src/Smalltalk/OpenSmalltalk/SqueakStable.app/Contents/MacOS/Squeak')
> #(1 '/Users/eze/.local/src/Smalltalk/Squeak/Squeak6.0-22104-64bit.image')
> #(2 'one')
> #(3 'two')
> #(4 'three')
> #(5 'four')

# Behaviour using the current release candidate VM
The transcript logs only the vm executable and the image
>#(0 '/Users/eze/.local/src/Smalltalk/OpenSmalltalk/SqueakRC.app/Contents/MacOS/Squeak')
>#(1 '/Users/eze/.local/src/Smalltalk/Squeak/Squeak6.0-22104-64bit.image')

Tested in both Cuis and Squeak.

Might be related to #655.

**Comment by krono** [comment]
Can you share the actual commandline please?

**Comment by stormwatch** [comment]
> Can you share the actual commandline please?

Sure thing!

cd to the image dir, then tried:

`/Users/eze/.local/src/Smalltalk/OpenSmalltalk/SqueakRC.app/Contents/MacOS/Squeak Squeak6.0-22104-64bit.image one two three four`

against:

`/Users/eze/.local/src/Smalltalk/OpenSmalltalk/SqueakStable.app/Contents/MacOS/Squeak Squeak6.0-22104-64bit.image one two three four`

and similarly for Cuis tried:

`/Users/eze/.local/src/Smalltalk/OpenSmalltalk/SqueakRC.app/Contents/MacOS/Squeak Cuis6.0-6090.image one two three four`

against:

`/Users/eze/.local/src/Smalltalk/OpenSmalltalk/SqueakStable.app/Contents/MacOS/Squeak Cuis6.0-6090.image one two three four`

**Comment by krono** [comment]
Yeah nobody is poulating `commandLineArguments`, I have a look

**Comment by krono** [comment]
Yeah, that was my fault, see 5b064fcae9254b60ac69e8a3b97c6c51629b9d48

**Comment by krono** [comment]
@marceltaeumel 1b15c7e0654934898eec152d231f87ab704d7040 is relevante for the RC. I'm sorry
